### ISSUE TITLE
RaspberryMatic CCU HA add-on - isn't stating after updating the host to Debian 12

### ISSUE THREAD

**Issue by Chris591** [jens-maus/RaspberryMatic#2358] opened 2023-07-12 16:27 UTC
### Describe the issue you are experiencing

updated the host to Debian 12
everything seems fine apart of the HA add-on RaspberryMatic.
if I activate the watchdog HA will reboot the add-on in a loop.
disabled it starts but you don't see the UI or any HA device is showing a state.

### Describe the behavior you expected

should run as before

### Steps to reproduce the issue

as described above - update the host to Debian 12
since then didn't found a way to get it working again.
tested to disable appamor bit didn't helped as well.

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
RaspberryMatic CCU
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet down, , OK
Identifying Homematic RF-Hardware: .......HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3.4, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3.4, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ..........FAIL
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: ....................ERROR
Starting HMIPServer: ........................................OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.7.20230626 (raspmatic_oci_arm64)
```

### Additional information

Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

docker-ce (5:24.0.4-1~debian.12~bookworm)

Home Assistant 2023.7.1
Supervisor 2023.07.1
Frontend 20230705.1 - latest

**Comment by Baxxy13** [comment] 2023-07-13 12:34
Sounds like #2353 
There is a possible solution linked which you can try.

**Comment by Chris591** [comment] 2023-07-13 13:13
> Sounds like #2353 
> 
> There is a possible solution linked which you can try.

Yes this helped but isn't secure as it should.

Disabling AppArmor with apparmor=0 on kernel commandline works around the issue.

**Comment by jens-maus** [comment] 2023-07-13 13:14
Ok, but then this definitely a duplicate of #2353 and indeed nothing for this project here but butter reported in the HomeAssistant projects accordingly.

**Closed by jens-maus** 2023-07-13 13:14 UTC
Labels: :bug: bug-report

**Comment by sbyx** [comment] 2023-07-13 13:27
Relevant HA issue for reference https://github.com/home-assistant/supervised-installer/issues/311
