### ISSUE TITLE
 .ova version 3.79.6.20241122 can't be installed on XCP-ng 8.3

### ISSUE THREAD

**Issue by fluxcondensator** [jens-maus/RaspberryMatic#2965] opened 2024-12-21 17:16 UTC
### Describe the issue you are experiencing

Hi there,
I'm using XCP-ng 8.3 where I tried to install the latest .ova version 3.79.6.20241122. 
It failed.

### Describe the behavior you expected

I tried backwards and found the last version which is fine to install is .ova version 3.73.9.20240130.

### Steps to reproduce the issue

1. Import .ova file via XOA webinterface.
2. Adjust wrong HDD capacity to 64GB.
3. Starting VM.
4. Boot post is visible on console.
5. Blank screen is visible a while.
6. VM restart.
7. Loops 3. to 6.
...

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
not applicable
```

**Comment by fluxcondensator** [comment] 2024-12-21 17:25
I forgot to mention: Any try to update 3.73.9.20240130 with newer versions up to 3.79.6.20241122 failed.

**Comment by jens-maus** [comment] 2024-12-21 20:51
Duplicate of #2752

**Closed** 2024-12-21 20:51 UTC
Labels: :bug: bug-report, :heavy_multiplication_x: duplicate
