### ISSUE TITLE
Raspberry pi zero assets for last release is missing

### ISSUE THREAD

**Issue by pgollor** [jens-maus/RaspberryMatic#1239] opened 2021-04-25 15:20 UTC
The assets for release https://github.com/jens-maus/RaspberryMatic/releases/tag/3.57.5.20210424 for the raspberry pi zero are missing. Or am I to stupid to find it?

**Comment by jens-maus** [comment] 2021-04-25 15:48
Duplicate of #1237

**Closed by jens-maus** 2021-04-25 15:48 UTC
