### ISSUE TITLE
Virtualize RaspberryMatic on Synology NAS

### ISSUE THREAD

**Issue by matt391a** [jens-maus/RaspberryMatic#507] opened 2018-12-03 08:29 UTC
Is there any chance to compile a RaspberryMatic / Buildroot package which can be executed in a x86/x64 virtual machine on my NAS virtual machine manager? Could someone provide such package or could anyone support me to create such?

**Comment by jens-maus** [comment] 2018-12-03 08:46
In principle it should be possible to create a docker/lxccu package right out of the RaspberryMatic/buildroot environment. However, nobody has yet taken the task to actually do that – also probably because this requires quite some deep knowledge about buildroot. And my time is already quite limited, I am afraid. In addition, IMHO such a critical system like a CCU should deserve an own system and should not be put on another host potentially imposing certain runtime problems, etc.

But in principle it should be technically possible, yes.

**Comment by clemz1986** [comment] 2018-12-03 22:43
This point is quite interesting with the docker image, however in my view it has limited sense, as the radio-module for the wireless connection to the various HMIP-elements cannot be directly attached, as the USB dongle is as far as i know only working with the classcial HM-components (non-IP). This point could be of novel interest with a new proper radiomodule adressing all possible HM components, however the market is quite limited for that I think, as a raspy has its advantages and is quite cheap to buy and to run. Besides that there are other projects out with docker images running OCCU, however I found the best support within this one runned by Jens Maus.

**Comment by jens-maus** [comment] 2018-12-14 09:02
Duplicate of #357

**Closed by jens-maus** 2018-12-14 09:02 UTC
Labels: duplicate, enhancement
