### ISSUE TITLE
BidCos-Wired broken in v3.41.11.20181124

### ISSUE THREAD

**Issue by r4m3u5** [jens-maus/RaspberryMatic#479] opened 2018-11-25 00:20 UTC
When opening the WebUI after upgrading to v3.41.11.20181124 this messages appears:

![image](https://user-images.githubusercontent.com/17406423/48974041-8176e180-f04d-11e8-9558-17ecee649314.png)

Although the RS485 gateway shows status 'connected' in the LAN gateway configuration section none of the wired devices can be used. E.g. when trying to switch an actuator to 'on' it just stays on 'off' not displaying any additional error message. The behavior is reproducible.
Downgrading to v3.37.8.20181026 solves the issue.

Cheers
/Jens

**Comment by jens-maus** [comment] 2018-11-25 00:53
Please post content of /var/etc/hs485d.conf and check if hs485d is running using `ps` command.

**Comment by alexreinert** [comment] 2018-11-25 09:18
Can you please provide your /etc/config/InterfacesList.xml

**Comment by HMside** [comment] 2018-11-25 10:01
The problem is that the Listen Port in/usr/local/config/hs485d. conf is still 2000. After modification to 32000 and a reboot will work again.

/var/etc/hs485d.conf
```
Listen Port = 32000
Log Destination = Syslog
Log Identifier = hs485d
[Interface 0]
Type = HMWLGW
Name = Wired-Gateway
Serial Number = KEQ0123456
Encryption Key = key
IP Address = 10.20.30.223
```
The Listen Port in /usr/local/etc/config/hs485d.conf is still 2000
```
Listen Port = 2000
Log Destination = Syslog
Log Identifier = hs485d
[Interface 0]
Type = HMWLGW
Name = Wired-Gateway
Serial Number = KEQ0123456
Encryption Key = key
IP Address = 10.20.30.223
```

**Comment by r4m3u5** [comment] 2018-11-25 12:17
Good stuff @HMside !

Can confirm that changing the listen port in /usr/local/etc/config/hs485d.conf to 32000 fixes the problem.

Cheers
/Jens

**Comment by jens-maus** [comment] 2018-11-25 15:34
I can confirm that changing `Listen Port` to `32000` in `/etc/config/hs485d.conf` solves the issue for a moment. So please everyone suffering from this issue should manually modify this file until the issue is permanently fixed in the next version.

**Comment by Erbit** [comment] 2018-11-25 20:09
I also confirm. Changing the port to 3200 in the /etc/config/hs485d.conf file solves the issue.

Thank you for the quick solution.

**Closed** 2018-11-25 22:17 UTC
Labels: bug, important
