### ISSUE TITLE
[bug] Cannot create new heating group

### ISSUE THREAD

**Issue by Sirs0ri** [jens-maus/RaspberryMatic#2159] opened 2023-01-13 02:30 UTC
### Describe the issue you are experiencing

I'm unable to create a heating group (HmIP-Heizungssteuerung) via the webinterface. 

After trying to save the new group, the loading-overlay just stays up indefinitely, and the API request to <ip>/pages/jpages/group/save?sid=<sid> never resolves. There's an error in /var/log/hmserver.log, see below.

### Describe the behavior you expected

The new group should be filled with the devices I have chosen. The group seems to be created successfully (it shows up in the list of groups after manually reloading the page), but my chosen devices aren't assigned.

### Steps to reproduce the issue

1. In the Web-UI, go to Eintellungen -> Gruppen
2. Press "Neu" at the bottom
3. Select HmIP-Heizungssteuerung (unsure if the other type of Heizungssteuerung is also affected, since I only own HmIP devices)
4. (optionally) Set a name for the group
5. Add one or more devices
6. Press "ok" at the bottom

You should see a popup that never goes away, saying:

> Gruppe wird gespeichert...
> Bitte warten. Die direkten Verknüpfungen werden konfiguriert.

### What is the version this bug report is based on?

3.65.11.20221218 (oci)

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
/ # cat /var/log/hmserver.log
2023-01-13 03:09:33,496 de.eq3.lib.groupadministration.GroupAdministrationService ERROR [vert.x-worker-thread-4] Error in propagateNewGroup
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method setReadyConfig: <class 'Exception'>:method "setReadyConfig" is not supported Code: 1
        at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
        at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
        at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
        at com.sun.proxy.$Proxy42.setReadyConfig(Unknown Source) ~[?:?]
        at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.createVirtualDevice(VirtualDeviceHandlerRega.java:279) ~[HMIPServer.jar:?]
        at de.eq3.ccu.groupdevice.hmip.service.HmIPGroupDeviceHandler.propagateNewGroup(HmIPGroupDeviceHandler.java:101) ~[HMIPServer.jar:?]
        at de.eq3.lib.groupadministration.GroupAdministrationService.propagateNewGroup(GroupAdministrationService.java:183) ~[HMIPServer.jar:?]
        at de.eq3.lib.groupadministration.GroupAdministrationService.createGroup(GroupAdministrationService.java:154) ~[HMIPServer.jar:?]
        at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:131) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
2023-01-13 03:09:33,509 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-4] Unhandled exception
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
        at com.google.gson.Gson.fromJson(Gson.java:818) ~[HMIPServer.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[HMIPServer.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[HMIPServer.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[HMIPServer.jar:?]
        at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:144) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[HMIPServer.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[HMIPServer.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[HMIPServer.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[HMIPServer.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[HMIPServer.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[HMIPServer.jar:?]
        ... 14 more
```

### Additional information

Environment: Running in Docker on a RasPi4 (4GB)

Please let me know if I can help with any other logs, replies in German and English are both fine for me!

**Comment by jens-maus** [comment] 2023-01-13 05:17
Duplicate of #2105

**Closed by jens-maus** 2023-01-13 05:17 UTC
Labels: :bug: bug-report
