### ISSUE TITLE
Webpage did not start on Home Assistant, but Raspberrymatic still working

### ISSUE THREAD

**Issue by Fiiti** [jens-maus/RaspberryMatic#2722] opened 2024-04-21 13:50 UTC
### Describe the issue you are experiencing

Clicking on "RaspberryMatic" in Home Assistant  did not start the Webpage.
I get shown "The add-on does not seem to be ready yet, maybe it is still starting. Do you want to try again?".

But the Add-On ist startet and green. 
Of course I restartet the add-on and the whole system many times.

Toda I updatet to the latest version: 3.75.7.20240420 - but I cannot say if this is the purpose of this issue.

### Describe the behavior you expected

CCU Startpage should be shown.

### Steps to reproduce the issue

Click on the PaspberryMatic Button direct in the left panel.

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
In Home Assistant  Journal itself:

 21 13:41:10 homeassistant homeassistant[516]: 2024-04-21 15:41:10.173 WARNING (MainThread) [aioesphomeapi.connection] athom-presence-sensor-f9a5bf @ 192.168.1.36: Connection error occurred: [Errno 104] Connection reset by peer


In the Webbrowser Window I see an 
`Error 502: Bad Gateway`

The Log in Home Assistant  for RaspberryMatic:
```
RaspberryMatic CCU
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: Intel Corporation NUC6CAYB (oci), OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:15.0-2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:15.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: /etc/config/CCU2GW0001.keychange OK
Starting SNMP daemon: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: ..........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.75.7.20240420 (raspmatic_oci_amd64)
```

In Supervisor Log 
`2024-04-21 15:13:46.027 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:default [Connect call failed ('172.30.33.1', 8099)]`
```

### Additional information

I did not know, how I can go back to the latest Version before.
Is it for tests possible?

I am also tried The HACS HMIP Integration to set to version 1.58.0 and tried also the Version 1.60b .

So what can I do?

**Comment by jens-maus** [comment] 2024-04-21 13:51
Duplicate of #2720

**Closed** 2024-04-21 13:52 UTC
Labels: :bug: bug-report, :heavy_multiplication_x: duplicate
