### ISSUE TITLE
Sun set and Sun rise to be used directly in the time control

### ISSUE THREAD

**Issue by AxelG-DE** [jens-maus/RaspberryMatic#791] opened 2020-02-29 15:48 UTC
**Is your feature request related to a problem? Please describe.**
I would like to address sunset and sunrise directly in my programs, so that I can say e.g. 2.5h before sunrise and 1.15h after sunrise

Currently I can merely use astro-day and astro-night, which do not provide me the flexibility which I could find from aforementioned proposal

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by jens-maus** [comment] 2020-04-02 09:28
Duplicate of #221

**Closed by jens-maus** 2020-04-02 09:28 UTC
