### ISSUE TITLE
HM Configuration Tool LAN not status 

### ISSUE THREAD

**Issue by jakespeed1311** [jens-maus/RaspberryMatic#185] opened 2017-11-06 21:35 UTC
Hallo,
is there an problem with the "HM Configuration Tool LAN" Adappter in the latest version ? The Status is not Displayed in Version 2.29.23.20171022.
I have  3 of these adapters, byed bevor the Langateway was on the marktet ! Is this Device supportet now?
And i tried to delete the 3 devices reboot and add it new, no luck.
greedings
Jake

PS: I tried to add it as Lan Gateway (read this in an foum) to test but don't work also!

**Comment by litti** [comment] 2017-11-07 07:34
Are you only using the HM-LAN-CFG without HM-MOD-UART? If yes, please read https://github.com/jens-maus/RaspberryMatic/issues/177, the issue is fixed and close this one. If not, please give more details about your structure and some logs here.

**Comment by jakespeed1311** [comment] 2017-11-07 23:40
hello,
yes i have only the 3 Lan gateways, but i don't have an error message when i configure an device.
Short way, YES this works on my System too, But if i restart the PI the file still is changed back to default and only the Name "Virtual Devices " is filled in. 
tanks
Jake
PS: Try to by the hm-occu-sdk module

**Closed** 2017-11-07 23:41 UTC
