### ISSUE TITLE
cannot maintain weekly program of HmIP-FSM16

### ISSUE THREAD

**Issue by olivermaul** [jens-maus/RaspberryMatic#1226] opened 2021-04-13 17:14 UTC
cannot maintain weekly program of HmIP-FSM16 (1.18.20). Already reset device to factory default.
it is not possible to make any changes to the weekly program of a HmIP-FSM16.
popup with "settings will be transmitted to devices. Please wait..." is coming but not finishing.

**Steps to reproduce the behavior**
1. go to a HmIP-FSM16 in Devices
2. go to Set
3. go down to weekly program (Ch. 7)
4. click Add
5. click OK

**Expected behavior**
new weekly program should be added.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: Raspi 3B+
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment] 2021-04-13 17:39
Duplicate of #1189

**Closed by jens-maus** 2021-04-13 17:39 UTC
