### ISSUE TITLE
groups can't be changed if there is a new device in the inbox

### ISSUE THREAD

**Issue by grunes** [jens-maus/RaspberryMatic#1437] opened 2021-10-04 10:52 UTC
**Describe the bug**
It's not longer possible to edit groups if there is a new device in the inbox. Web-UI is freezing during device configuration. Seams to be a re-bug of #945 

**Steps to reproduce the behavior**
1. Add a new device, must be in the inbox ("Posteingang")
2. Edit a group (e.g. remove a device) 
3. press OK button

**Expected behavior**
group should be saved without the deleted device.

**Screenshots**
![image](https://user-images.githubusercontent.com/36551079/135837283-063af3fa-a102-48a3-b29d-51b9d89aa0fd.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: Asus Tinker Board S
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
after removing the new device from the inbox, the group can be saved as expected.

**Comment by jens-maus** [comment] 2021-10-05 10:41
Usual question: @Baxxy13 @jp112sdl can you reproduce this issue? My feeling is that this might be some internal issue in the web parts in `HMIPServer` which we don't have access to in the end. Would be great if someone can try to reproduce it.

**Comment by jp112sdl** [comment] 2021-10-05 11:32
I cannot test adding/removing devices to an HmIP-group, because I have no HmIP devices.

But with having a BidCos device in the inbox, I can create/delete/edit a "classic HM" group without any error and I can create/delete an empty HmIP-group, too.

**Comment by Baxxy13** [comment] 2021-10-05 17:56
I can reproduce this and maybe found something.
The teached in device (HmIP-SCI in this case) which is still located in the inbox will showed as an addable device.
![IP-GRUPPE bei Gerät im Posteingang_A](https://user-images.githubusercontent.com/54898249/136076524-64068696-3265-468b-916e-5ec004216d64.JPG)
Adding this strange device or any other possible device ends up in the rotating circle.
![IP-GRUPPE bei Gerät im Posteingang_B](https://user-images.githubusercontent.com/54898249/136076689-8994d202-f50e-4ffe-a23f-3e006e978dbe.JPG)

Sorry für's holprige Englisch. Darf gerne korrigiert werden.

**Comment by grunes** [comment] 2021-10-06 05:23
We even can switch to German!

**Comment by grunes** [comment] 2022-01-31 15:16
any updates?

**Comment by rene-re** [comment] 2022-12-22 15:47
- I cannot add any devices to a group. 
- Stuck with "Gruppe wird gespeichert"
- Inbox is empty
- Running version 3.65.11.20221218

![image](https://user-images.githubusercontent.com/1926425/209170989-5c95a0d7-e329-42e8-a279-465a5a64c11c.png)

**Comment by Baxxy13** [comment] 2022-12-22 15:55
Known problem in the actual RaspberryMatic.
Solutions:
- Downgrade
- use actual Nightly Snapshaot
- repair it "manually" --> [see here](https://homematic-forum.de/forum/viewtopic.php?f=65&t=77164)

**Comment by jens-maus** [comment] 2022-12-22 16:03
You forgot to mention also: Read carefully through an existing ticket/issue before hijacking it because this issue here is substantially different because it relates to the point that adding groups is not possible if there is a device waiting in the inbox!

**Comment by rene-re** [comment] 2022-12-22 16:05
Thanks, noted @jens-maus  @Baxxy13

**Comment by sikraemer** [comment] 2024-01-29 22:52
Hi,

I ran into this issue today. Same error message as in the original post.
My setup is running on version 3.73.9.20231130 on a RPi4 through the HomeAssistant Addon.

I could pinpoint the error to occur [here](https://github.com/eq-3/occu/blob/master/HMserver/opt/HMServer/pages/GroupEditPage.ftl#L540).
Generally when devices are added to the `assignableDevices` of the `viewModel` [here](https://github.com/eq-3/occu/blob/master/HMserver/opt/HMServer/pages/GroupEditPage.ftl#L261), the `device` member is not set if the device is still in the inbox.

I am not sure if the problem is caused by the response caused by either of these 3.
Each of them can be adjusted to fix the problem.
* the API response from `/pages/jpages/group/suitableGroupMembers` - since the devices don't seem to be suitable
* the part that adapts the json response into the `assignableDevices` of the `viewModel`
* the part when the remaining `assignableDevices` are marked as not in the group without checking if the `device` member even exists

Any input on the direction of how the fix should be applied would be appreciated.

**Closed** 2024-11-01 08:24 UTC
Labels: :bug: bug-report, :label: WebUI
