### ISSUE TITLE
Add HMIP-SWDO to group not working

### ISSUE THREAD

**Issue by RunRudi** [jens-maus/RaspberryMatic#2117] opened 2022-12-23 15:48 UTC
### Describe the issue you are experiencing

RaspberryMatic is running on HomeAssistant, installed on RaspberryPi3B+

Raspberrymatic: 3.65.11.20221218

HomeAssistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest

HMIP-SWDO cannot be added to an existing (2x HmIP-eTRV-2 already inside) or new group.
You can add the SWDO to the group but if you click "OK" the load screen not finishes (see picture)
![Failure](https://user-images.githubusercontent.com/110335726/209361772-8449fabb-4ceb-485b-a899-0985d4e28dd3.JPG)

### Describe the behavior you expected

SWDO gets part of the group

### Steps to reproduce the issue

1. Add new SWDO to Raspberry matic
2. Go to new device inbox
3. Go to group page
4. add new device out of the list of avalible devices
5. click ok
...

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
2022-12-23 16:00:57,989 de.eq3.cbcs.util.EQ3LoggerOutputStream ERROR [HmIP-RF_java_WorkerPool-0] Dec 23, 2022 4:00:57 PM org.apache.http.impl.client.DefaultHttpClient tryExecute 
2022-12-23 16:00:57,991 de.eq3.cbcs.util.EQ3LoggerOutputStream ERROR [HmIP-RF_java_WorkerPool-0] INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Broken pipe (Write failed) 
2022-12-23 16:00:57,995 de.eq3.cbcs.util.EQ3LoggerOutputStream ERROR [HmIP-RF_java_WorkerPool-0] Dec 23, 2022 4:00:57 PM org.apache.http.impl.client.DefaultHttpClient tryExecute 
2022-12-23 16:00:57,996 de.eq3.cbcs.util.EQ3LoggerOutputStream ERROR [HmIP-RF_java_WorkerPool-0] INFO: Retrying request to {}->http://127.0.0.1:39292 
2022-12-23 16:09:33,820 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-17] Unhandled exception 
java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field de.eq3.cbcs.legacy.bidcos.rpc.objects.DeviceDescription.children to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_352]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_352]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:1.8.0_352]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_352]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcField.setValue(RpcField.java:69) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseObject(XmlRpcParser.java:447) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:392) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseArray(XmlRpcParser.java:519) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:385) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:163) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy40.listDevices(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.updateDevicesForClient(BackendUpdateDevicesCommand.java:34) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.run(BackendUpdateDevicesCommand.java:29) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:27) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:11) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
2022-12-23 16:30:17,730 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-14] Unhandled exception 
java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field de.eq3.cbcs.legacy.bidcos.rpc.objects.DeviceDescription.children to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_352]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_352]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:1.8.0_352]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_352]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcField.setValue(RpcField.java:69) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseObject(XmlRpcParser.java:447) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:392) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseArray(XmlRpcParser.java:519) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:385) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:163) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy40.listDevices(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.updateDevicesForClient(BackendUpdateDevicesCommand.java:34) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.run(BackendUpdateDevicesCommand.java:29) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:27) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:11) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
2022-12-23 16:31:52,749 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-10] Unhandled exception 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:144) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[HMIPServer.jar:?]
	... 14 more
2022-12-23 16:32:22,253 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
	at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
```

**Comment by jens-maus** [comment] 2022-12-23 17:00
Same, same, but different:

duplicate of #2105

**Closed by jens-maus** 2022-12-23 17:00 UTC
Labels: :bug: bug-report
