### ISSUE TITLE
Can't teach-in HmIPW-DRAP

### ISSUE THREAD

**Issue by derco0n** [jens-maus/RaspberryMatic#1350] opened 2021-07-18 16:24 UTC
**Describe the bug**
Unable to connect with HM IpW DRAP using the "Geräte anlernen"-functionality.
Neither in online or offline-mode (using KEY and SGTIN).

**Steps to reproduce the behavior**
1. Setup a new raspberrymatic installation
2. clicked on "Geräte anlernen" (using german UI)
3. distributed Power to the DRAP
4. in the lower, left pane (Homematic IP), clicked on "HmIP Gerät anlernen" as described in the systems-manual ( https://www.homematic-ip.com/downloads/download/handbuecher/HmIPW-Systemhandbuch.pdf ) on page 77
5. distributed Power to the DRAP
6. Waited for 60 seconds
7. As this doesn't give any new devices in "Posteingang" tried the same procedure in local-mode, using KEY and SGTIN in the lower right mode

**Expected behavior**
Expected to find a new device (DRAP) in "Posteingang" or at least an error message which might give some hints.

**System information:**
 - RaspberryMatic Version: 3.59.6.20210703
 - DRAP-Firmware Version: 2.2.16
 - Used Hardware: Raspberry Pi 3B+
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
- This is a new setup, with a brand new DRAP and RPI-RF-MOD.
- Actually found DRAP and CCU (Raspberrymatic) using netfinder-tool by EQ3.
- Watching the traffic with wireshark, it looks like the DRAP is joining/creating a multicast-group on startup.
- Using a OpenWRT-Router as a switch, with IGMP disabled.

**Comment by g00gll** [comment] 2021-07-20 10:35
Same behaviour with my new installation. Descriped in the forum: https://homematic-forum.de/forum/viewtopic.php?f=65&t=68630
in the meantime i installed 3.57.5.20210424 and can add the drap.
Tried bevor withg Raspi 3 & 4 and 2 brand new Draps.

**Comment by jens-maus** [comment] 2021-07-20 11:24
@g00gll Can you please try to reproduce your observations by unteaching your DRAP and then going RaspberryMatic versions up until the teach-in of the DRAP does not work anymore? At which RaspberryMatic the teach-in of a DRAP actually stops working?

**Comment by hellboy-wien** [comment] 2021-07-25 19:20
Hatte das gleiche bei mir lag es anscheinend an der "Connect Box" von meinem Anbieter. Hab dann auf einen SG300 gewechselt und dann konnte ich zumindest mal die Geräte anlernen....

Aber nach kurzer Zeit "Geräte Kommunikation gestört...." 
Hab dann gestern mal Drap auf die neuerste Version via Web GUI upgedatet... und jetzt geht gar nix mehr....

Werde Morgen mal einen Request schreiben.

**Comment by bergernetch** [comment] 2021-08-05 19:51
Hab das gleiche Problem, bis jetzt ohne Lösung.

**Comment by bergernetch** [comment] 2021-08-05 22:31
After a downgrade to 3.55.10.20210213 I could teach in the HmIPW-DRAP as well as the HmIP-HAP immediately without issues. With 3.59.6.20210703 it was not possible without any indication about an error.

**Comment by jens-maus** [comment] 2021-08-06 06:28
@bergernetch Same as for @g00gll: Can you please try to reproduce your observations by unteaching your DRAP and then going RaspberryMatic versions up until the teach-in of the DRAP does not work anymore? At which RaspberryMatic the teach-in of a DRAP actually stops working?

**Comment by ThomasSiegmund** [comment] 2021-08-06 14:23
Hi Jens,

as written here, I can reproducibly teach in HAPs and DRAPS using RaspberryMatic-3.57.5.20210525-rpi4, but not at all with RaspberryMatic-3.59.6.20210703-rpi4. I've searched quite a bit in the log files, but did not find any smoking gun.

My setup:
- RaspberryMatic und RedMatic on Raspi 4* in a Docker-Container under Ubuntu
- RPI-RF-MOD on HB-RF-USB-2
- a few Homematic components for testing (HmIP-WRCR, HmIP-WRC6, HMIP-PSM. 2 x HAP, 2 x DRAP)

For testing I have used fresh Raspberrymatic installations on SD card, without the Docker environment.

If you have ideas how to further narrow down the problem, please let me know.

Thomas

**Comment by bergernetch** [comment] 2021-08-08 23:23
@jens-maus as suggested, I did a few tries with different versions, I used the RaspberryMatic update mechanism.

I went through:
3.55.10.20210213 
3.57.5.20210525
3.59.6.20210703 
3.59.6.20210807

Now it works with all of them. Does it matter if I use the update function, or should I do it again using an SDcard overwrite?

My setup:

- Raspberry Pi 4 with RPI-RF-MOD
- HmIPW-DRAP, HmIP-HAP and a few more components.

What do you suggest?

**Comment by derco0n** [comment] 2021-08-09 03:43
> @jens-maus as suggested, I did a few tries with different versions, I used the RaspberryMatic update mechanism.
> 
> I went through:
> 3.55.10.20210213 
> 3.57.5.20210525
> 3.59.6.20210703 
> 3.59.6.20210807
> 
> Now it works with all of them. Does it matter if I use the update function, or should I do it again using an SDcard overwrite?
> 
> My setup:
> 
> - Raspberry Pi 4 with RPI-RF-MOD
> - HmIPW-DRAP, HmIP-HAP and a few more components.
> 
> What do you suggest?

It didn't work for me with 3.59.6.20210703 flashed on a brand new sd-card used in a Pi3.
Could be that there's a difference between pi3 and Pi4 or that the update-function works slightly different than flashed directly.
To verify, i suggest to test flashing the versions directly.
Sincerely.

**Comment by ThomasSiegmund** [comment] 2021-08-09 07:12
For me the problem is also gone. I did  the tests described above with freshly downloaded images. The problem was definitively real last week, but was gone when I wanted to do some more tests Friday evening. I don't think it's a Pi3 vs. Pi4 issue, because I noticed the problems on a Pi4 while another user of the HomeMatic Forum reported the issue on a Pi3.

I noticed one additional thing: over the last moths when I did my first experiments with HomeMatic IP, registering devices via Internet never worked for me. I could only use the 'local' method by entering device id and key. Now suddenly also the internet method works. Maybe just a coincidence. But perhaps there was a change of the EQ3 server infrastructure involved.

**Comment by jens-maus** [comment] 2021-08-09 08:49
> But perhaps there was a change of the EQ3 server infrastructure involved.

This could also very be the case, yes. So the only remaining issue regarding teach-in of a HmIPW-DRAP is now when trying to teach-in a HmIPW-DRAP when running RaspberryMatic as a HomeAssistant Add-on or as a docker container, right? Or does the teach-in work, but the connection / led of the DRAP does not stop to blink due to the missing multicast connection within the docker environment?

**Comment by ThomasSiegmund** [comment] 2021-08-09 09:49
As stated otherwise, in my experience a registered DRAP cannot connect to RaspberryMatic if it's running in a Docker container. This is because of UDP broadcast messages from the DRAP not reaching the Docker internal network. As far as I can tell, this problem is clearly unrelated to the issues discussed here. If you wish I can start a new issue for this.

**Comment by derco0n** [comment] 2021-08-09 10:11
> > But perhaps there was a change of the EQ3 server infrastructure involved.
> 
> This could also very be the case, yes. So the only remaining issue regarding teach-in of a HmIPW-DRAP is now when trying to teach-in a HmIPW-DRAP when running RaspberryMatic as a HomeAssistant Add-on or as a docker container, right? Or does the teach-in work, but the connection / led of the DRAP does not stop to blink due to the missing multicast connection within the docker environment?
> 

Please note, that the described problem did occur on bare metal hardware. No docker or virtualisation has been involved in my case.

I can try to verify if the problem seems resolved.

However: how is the communication between DRAP and Raspberrymatic handled, as a serverchange on EQ3-side seems highly unlikely to me, if communication is done just locally.

**Comment by jens-maus** [comment] 2021-08-09 10:52
> If you wish I can start a new issue for this.

Yes, please do so and put the results of your own analysis there please.

**Comment by jens-maus** [comment] 2021-08-09 10:55
> However: how is the communication between DRAP and Raspberrymatic handled, as a serverchange on EQ3-side seems highly unlikely to me, if communication is done just locally.

Well, this ticket is about the teach-in process of a HmIPW-DRAP and AFAIK this teach-in process is largely assisted by the eQ3 server infrastructure, thus requires connection to the eQ3 servers. But as soon as the DRAP was successfully teached-in, all further communication is done local only.

**Comment by jens-maus** [comment] 2021-08-31 08:23
After having fixed #1387 I think this issue here might be perfectly related to it (RPI-RF-MOD firmware not updated properly to 4.4.26 and thus no current DRAP teach-in functionality). So please try a recent nightly snapshot or wait until the next version is released in september. This should solve all these teach-in issues with a HmIPW-DRAP and using a RaspberryPi3/Pi4 as the base host for RaspberryMatic.

**Closed by jens-maus** 2021-08-31 08:23 UTC
Labels: :bug: bug-report
