### ISSUE TITLE
CRITICAL Bug with HmIP-eTRV-2 Max open position/adjusting settings in WebUI

### ISSUE THREAD

**Issue by klour** [jens-maus/RaspberryMatic#1807] opened 2022-04-17 20:47 UTC
### Describe the issue you are experiencing

When adjusting settings of HmIP-eTRV-2 (e.g. time windows for heating periods) the max. opening position falls to 0%. Faulty position is also not good, I think. 
The critical point is, that the max opening position cannot be set back to 100 or 95%. It remains at 0% after saving. Furthermore I cannot choose 100%, only 95% which is also a bug in WebUI.
As a result, all HmIP-eTRV-2 become useless! No boost, no valve opening at all happens! So no heating.

The issue is not present right after a HmIP-eTRV-2 was added freshly to the CCU. It occurs, right after time or settings adjustement of this device takes place in WebUI. To solve this, user needa to delete the device again out of the CCU, until next settings adjustment. So no real settings adjustment ca take place at all.

Tested with Chrome and Edge using the latest RaspberryMatic release.

### Describe the behavior you expected

The mentioned features worked without issues with earlier versions of Raspberrymatic.

### Steps to reproduce the issue

see above.

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no log, easy to reproduce.
```

**Comment by jens-maus** [comment] 2022-04-18 04:52
Duplicate of #1784

**Closed** 2022-04-18 04:53 UTC
Labels: :bug: bug-report, :heavy_multiplication_x: duplicate
