### ISSUE TITLE
Umlaute Problem

### ISSUE THREAD

**Issue by holle72** [jens-maus/RaspberryMatic#2193] opened 2023-01-30 13:56 UTC
### Describe the issue you are experiencing

Umlaute werden nicht richtig angezeigt.

### Describe the behavior you expected

Umlaute anzeigen.

### Steps to reproduce the issue

![16750866032341446235483162299088](https://user-images.githubusercontent.com/28810042/215495475-16ac7000-b24b-4c14-bd58-716041f3df92.jpg)
![16750866826636975115927396663514](https://user-images.githubusercontent.com/28810042/215495618-7f4f9823-ddb5-40ae-bf62-4302c3c10022.jpg)

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Kann ich keine Angaben zu machen.
```

**Comment by jens-maus** [comment] 2023-01-30 13:58
Duplicate of #2160

**Closed by jens-maus** 2023-01-30 13:58 UTC
Labels: :bug: bug-report
