### ISSUE TITLE
Change behaviour of system variable "Presence ??" in German "Anwesenheit"

### ISSUE THREAD

**Issue by PaulMerk** [jens-maus/RaspberryMatic#250] opened 2018-01-21 21:10 UTC
System variable "Anwesenheit" is TRUE after system start. This is a trap for new users who expect, that the last state is remaining after system restart, as all other variables. They will be surprised when after power interruption and restart during their holidays the system is working as if they were at home.

Many users have taken into account this behaviour to prevent unwanted start of programs after restart.

proposal:
keep state of variable "Anwesenheit" after restart
create new system variable (e.g. "CCU2Reboot") which is always TRUE after restart and can be used to avoid unwanted start of programs after restart.

**Comment by jens-maus** [comment] 2018-02-13 15:58
This is a duplicate of #223

**Closed by jens-maus** 2018-02-13 15:58 UTC
