### ISSUE TITLE
Missing variable Names

### ISSUE THREAD

**Issue by odin568** [jens-maus/RaspberryMatic#66] opened 2017-02-16 07:26 UTC
Hi,
on booting, it seems some Language-Variables are missing:
![ccunotready](https://cloud.githubusercontent.com/assets/25813640/23011457/661a6ddc-f421-11e6-8411-4ff1349032cb.png)

**Comment by jens-maus** [comment] 2017-02-16 07:33
Duplicate of #46

**Closed by jens-maus** 2017-02-16 07:33 UTC
