### ISSUE TITLE
Changeble Order of Actions and Conditions in Programs 

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#2316] opened 2023-05-14 11:06 UTC
### Describe the solution you'd like

It would be good if it would be possible to change the order of actions to be performed by a program (if more than one action is configured) by arrow symbols (move up /move down).
Also for conditions this would be helpful to keep a good overview.
For conditions this should be possible for single conditions in one secion (all conditions are coupled by AND or OR) but also for the order of these sections.

### Describe alternatives you've considered

It is still possible to take a screen shot or the current configuration delete the actions /conditions and to enter them again (in the now correcte/better order.

### Is your feature request related to a problem?

Time consumtion is very high if actions/conditions must be deleted and entered new only to change its order.

**Comment by jens-maus** [comment] 2023-05-14 11:51
This is a duplicate of #1081 and #860.

**Closed by jens-maus** 2023-05-14 11:51 UTC
Labels: :bulb: enhancement-ideas
