### ISSUE TITLE
Stop booting at LGW Firmwareupdate

### ISSUE THREAD

**Issue by FraatRamski** [jens-maus/RaspberryMatic#44] opened 2017-01-10 12:50 UTC
Hallo,
i have installed the newest build and it worked fine. I have tested basics and I was able to connect devices. Than I have restored settings from CC2 same build version as RasberryMatic. The System is now hanging at LGWF Firmwareupdate.

**Comment by jens-maus** [comment] 2017-01-10 13:12
Please provide more information. Please press ALT+F2 to show the bootup console and see if it outputs any errors there.

**Comment by FraatRamski** [comment] 2017-01-10 13:26
Hallo, thanks for the fast answer.
modprobe: FATAL: module ehci_hcd not found in Directory /lib/modules/4.4.36-v7

**Comment by jens-maus** [comment] 2017-01-10 13:27
This is not an error message related to this issue. Please have a look at the point where the LGWFirmwareUpdate is applied. Is there written "OK" after it or not.

**Comment by PhilipHanebeck** [comment] 2017-01-10 18:24
Hello,
I've the same issue, two days ago I converted my ccu2 to the RaspberryMatic.
Yesterday I did some changes on a script and by saving this the RaspberryMatic did not respond, after plug off the power and plug it in again the RaspberryMatic hangs on booting at "LGW Firmewareupdate" (see Screenshot below) 
![2017-01-10 19 01 01](https://cloud.githubusercontent.com/assets/25038756/21818940/fd0e89dc-d769-11e6-8cc9-ede70d938995.jpg)
If I disconnect the LAN cable the "LGW Firmwareupdate" continues to "Firmwareupdate" (than I connect the LAN cable again and the RaspberryMatic comes up completly).
Please tell me how I can fix this problem.

**Comment by jens-maus** [comment] 2017-01-10 19:59
Before we can fix this we have to identify the root cause of the issue. So are you able to login to RaspberryMatic via SSH when this problem happens? If so, please have a look at `/var/log/messages` if there are any problems reported regarding the LAN gateway firmware update.

**Comment by jens-maus** [comment] 2017-01-10 20:02
And also please show the content of your `/etc/config/rfd.conf` file so that I can try to reproduce this issue.

**Comment by PhilipHanebeck** [comment] 2017-01-10 20:34
Thanks for your quick response, here are the desired files:

[files.zip](https://github.com/jens-maus/RaspberryMatic/files/697276/files.zip)

**Comment by jens-maus** [comment] 2017-01-10 20:43
@PhilipHanebeck Sorry, but are these files really taken AFTER RaspberryMatic got stuck or did you download these files after you booted it with a disconnected LAN cable? I really need the `/var/log/messages` file right after RaspberryMatic got stuck and NOT after you fixed/worked around it.

In addition, please note the following observations:

- Do you really have a LAN Gateway running? And is it reachable? Your /var/log/messages file is full of `Could not connect to HomeMatic Lan Gateway with IP Address 192.168.10.47` messages.
- You unfortunately attached the `/etc/config/hs485d.conf` file with the encryption key visible in there. So you would need to change it at some point now that anyone knows it.

**Comment by PhilipHanebeck** [comment] 2017-01-10 21:05
ok, now I've attached the actual lines from messages while RaspberryMatic is connected to LAN and didn't booted completly.
I've a LAN Gateway, but I just realized that the IP 192.168.10.47 is not correct, so I changed the IP to the actual IP (192.168.10.15) and I rebootet the RaspberryMatic, but the issue is still the same.
[Messages.txt](https://github.com/jens-maus/RaspberryMatic/files/697328/Messages.txt)

**Comment by jens-maus** [comment] 2017-01-10 21:08
Have you already tried to remove the LAN Gateway completely using the WebUI and readied it again?

**Comment by PhilipHanebeck** [comment] 2017-01-10 21:17
Now it works, after I changed the IP address of my LAN Gateway the first reboot failed, but after this I rebootet again with disconnected LAN (and connect the LAN cable after reboot was completed) the RaspberryMatic shoes that the LAN Gateway was now connected. Than I rebootet the system with LAN connection again and everything works fine.
Thanks a lot for you quick helping hands.
Now I'am looking forward to your next Firmware update of RaspberryMatic so I can use my Homematic IP devices with my raspberry pi 3.

**Comment by jens-maus** [comment] 2017-01-10 21:20
Thanks for double checking. I guess I will add some checks/output on the LAN Gateway IP addresses so that users can more easily identify an incorrect setup.

@FraatRamski Have you also checked your `/etc/config/hs485.conf` file and double checked that the IP address of your LAN Gateway is setup correctly?

**Comment by PhilipHanebeck** [comment] 2017-01-11 16:34
@jens-maus: is RaspberryMatic also avaiable for banana PI ?

**Comment by jens-maus** [comment] 2017-01-11 16:35
@PhilipHanebeck Sorry, but this is not only off-topic in here but also clearly stated on the main page and documentation: only RaspberryPi2 and RaspberryPi3.

**Comment by jens-maus** [comment] 2017-01-11 16:43
Now that this issue seems to be solved, I am going to close this issue.

**Comment by StephanTexxpro** [comment] 2017-01-13 13:19
Sorry to come back to this, same issue here with a HomeMatic RS485 Gateway.

Double checked IP settings, reachabilty, disabled IPV6, removed the device via Webinterface and reinstalled it.

Only killing '{S58LGWFirmwareU} /bin/sh /etc/init.d/S58LGWFirmwareUpdate start' allows the system to start up.

Environment: Pi3, Beta3, Restore from Backup (2.25.15)

**Comment by jens-maus** [comment] 2017-01-13 13:24
I am reopening that issue for the time being, however, I still feel that this is actually a user problem where the LAN gateway seems to be unreachable at the time when the firmware update is about to be applied. As I don't have a LAN Gateway myself I wonder what other users might have to contribute here?

@wowi1968 Do you have any idea what might stop the LAN Gateway firmware update? And how to actually debug this situation?

**Comment by jens-maus** [comment] 2017-01-13 13:31
@StephanTexxpro Can you please try the following command executions to actually debug the problem:

```
/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 0 -c
```

```
/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 0 -console
```

```
/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 0 -console
```

And please see which of the executions actually start to hang and please report the output here.

**Comment by StephanTexxpro** [comment] 2017-01-13 13:39
Hi Jens,

here we go:

`# /bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 0 -c
2017/01/13 13:33:25.359 <Debug> firmware filename is: coprocessor_update_hm_only.eq3`

`# /bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 0 -console
2017/01/13 13:33:40.790 <Info> No gateway found in config file /etc/config/rfd.conf`

`# /bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 0 -console
2017/01/13 13:33:50.700 <Info> LAN Gateway Firmware Update...`

`2017/01/13 13:33:50.700 <Info> Gateway MEQ0673117`

`2017/01/13 13:33:52.705 <Info> Gateway type is eQ3-HMW-LGW-App
cryptEnabled true2017/01/13 13:33:52.707 <Info> Available Firmware Version:   1.0.5`

`2017/01/13 13:33:52.707 <Info> Lan Gateway Firmware Version: 1.0.5`

`2017/01/13 13:33:52.707 <Info> Firmware is up to date`


Best,
Stephan

**Comment by jens-maus** [comment] 2017-01-13 13:41
@StephanTexxpro And which one of these command actually start to freeze/hang? You also have to make sure that you execute these commands right when your System hangs and you login in parallel via SSH.

**Comment by jens-maus** [comment] 2017-01-13 13:46
@StephanTexxpro Please also check if the file `/var/status/hasIP` exists when then freeze during bootup happens.

**Comment by StephanTexxpro** [comment] 2017-01-13 13:53
OK, system is stuck in reboot, output as follows:

/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 0 -c
2017/01/13 13:50:18.612 <Debug> firmware filename is: coprocessor_update_hm_only.eq3

/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 0 -console
2017/01/13 13:50:27.268 <Info> No gateway found in config file /etc/config/rfd.conf

 /bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 0 -console
2017/01/13 13:50:33.554 <Info> LAN Gateway Firmware Update...

2017/01/13 13:50:33.554 <Info> Gateway MEQ0673117
2017/01/13 13:50:35.560 <Info> Gateway type is eQ3-HMW-LGW-App
cryptEnabled true2017/01/13 13:50:35.561 <Info> Available Firmware Version:   1.0.5

2017/01/13 13:50:35.561 <Info> Lan Gateway Firmware Version: 1.0.5

2017/01/13 13:50:35.561 <Info> Firmware is up to date

cat /var/status/hasIP

=> emtpy (-rw-r--r--    1 root     root             0 Jan  1  1970 /var/status/hasIP)

Best,
Stephan

**Comment by jens-maus** [comment] 2017-01-13 13:55
@StephanTexxpro Hmm. strange. So I guess no command I told you gets stuck, right? Can you then please execute the following command if the system is stuck, so that we can see which process actually stops:

```
ps aux | grep eq3configcmd
```

**Comment by StephanTexxpro** [comment] 2017-01-13 14:25
Right, nothing got stuck.

`ps aux | grep eq3configcmd
  330 root     /bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 1
  800 root     grep eq3configcmd`

**Comment by jens-maus** [comment] 2017-01-13 14:29
@StephanTexxpro Can you please try to add a "sleep 5" at the very top of the start()` function in the `/etc/init.d/S58LGWFirmwareUpdate` file and then reboot the system to see if the problem is solved?

**Comment by StephanTexxpro** [comment] 2017-01-13 14:40
Up & running :)

Thank you very much!

What was the root cause?

**Comment by jens-maus** [comment] 2017-01-13 14:41
I think this is a runtime problem that the network might not be fully up at the time when this command is executed. Please reduce it to 4, then 3, then 2, then 1 and report back at which point it started to fail again.

**Comment by StephanTexxpro** [comment] 2017-01-13 14:47
`sleep 1` is enough.

**Comment by jens-maus** [comment] 2017-01-13 14:47
ok, thanks. I will see what I can do for the next beta to work around this problem.

**Comment by jens-maus** [comment] 2017-01-17 21:39
Reopening this issue since there are recent reports (see http://homematic-forum.de/forum/viewtopic.php?f=65&t=34497&p=335033#p335073) that the issue isn't solved yet.

**Closed** 2017-01-17 22:50 UTC
Labels: bug

**Comment by ahutchinson** [comment] 2017-03-05 21:43
I would like to confirm that I am still seeing this issue with Beta 4.  Sometimes the box will boot, but generally I have to kill:

{S58LGWFirmwareU} /bin/sh /etc/init.d/S58LGWFirmwareUpdate start
/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1

to get the Raspberry Pi to boot.

**Comment by jens-maus** [comment] 2017-03-05 22:06
Wait until beta5, this version should fix these issues.

**Comment by ahutchinson** [comment] 2017-03-05 22:24
Ok, thanks for the update.
