### ISSUE TITLE
HMIP-HAP with Home Assistant Raspberrymatic Plugin possible?

### ISSUE THREAD

**Issue by Rohrleitner** [jens-maus/RaspberryMatic#1755] opened 2022-03-11 11:38 UTC
### Describe the issue you are experiencing

I have tried to use a 2 different HMIP-HAP on RaspberryMatic CCU version: 3.61.7.20220226.
i can not find them! I have installed also a standalone Raspberrymatic Installation on a Pi4 with Version 3.61.7.20220310 (nigthly build) and everything works fine!
Is there something missing in the "Home Assistant" Version. It runs also on a Pi4 and i use the same HmIP-RFUSB Stick
I use

### Describe the behavior you expected

Works fine an standalone Pi4 with Version 3.61.7.20220310

### Steps to reproduce the issue

1. Newest Version RaspberryMatic CCU version: 3.61.7.20220226 for Home Assistant
2. Both HmIP-HAPs newest Firmware and reseted
3. Same AccesPoints and same HmIP-RFUSB on both installations
standalone works Home Assistant Version do not find the APs

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Where can i find the logs for Raspberrymatic in Home Assistant?
```

**Comment by jens-maus** [comment] 2022-03-11 13:01
Duplicate of #1373

**Closed by jens-maus** 2022-03-11 13:01 UTC
Labels: :bug: bug-report
