### ISSUE TITLE
TypeError in browser by trying to update firmware version of device

### ISSUE THREAD

**Issue by floriandrott** [jens-maus/RaspberryMatic#770] opened 2020-02-08 10:48 UTC
**Describe the bug**
I can't update the version version of my device. The reason is that when I click on 'update' within the WebUI then I get in my browser (Safari) a TypeError error in the console (Safari). I tried this out also in Chrome.

**To Reproduce**
1. Go to 'Startseite > Einstellungen > Geräte-Firmware - Übersicht'
2. Click on 'Update'
3. Nothing happens
4. Open developer tool in the browser to see the console
5. See typeError

**Expected behavior**
Firmware update is starting.

**Screenshots**
<img width="1668" alt="Bildschirmfoto 2020-02-08 um 11 46 40" src="https://user-images.githubusercontent.com/53261305/74083837-b4e23800-4a68-11ea-8f9f-22fc64b54554.png">
<img width="1668" alt="Bildschirmfoto 2020-02-08 um 11 46 25" src="https://user-images.githubusercontent.com/53261305/74083838-b57ace80-4a68-11ea-92bc-3648372198da.png">

**System information (please complete the following information):**
 - Version RaspberryMatic 3.49.17.20200131
 - Hardware Proxmox

**Additional context**
Was also existing in the previous RaspberryMatic version

**Comment by floriandrott** [comment] 2020-02-10 06:57
Is there a workaround to update the firmware of device? Due to the error I can't update the firmware.

**Comment by jens-maus** [comment] 2020-02-10 08:16
Please wait until the next coming RaspberryMatic update (or until RaspberryMatic beta versions appear) which will be based on 3.51.6 OCCU which potentially could fix the issue

**Comment by jens-maus** [comment] 2020-02-10 13:55
@floriandrott I just updated RaspberryMatic to OCCU 3.51.6 today and generated new experimental beta versions. So if you are brave and would like to give it a test so that we can check before the final release that the issue is eiterh solved in 3.51.6 or that we need to fix it ourself, please download the experimental version here: https://github.com/jens-maus/RaspberryMatic/actions/runs/36918297 and let me know if this version solves your issues.

**Comment by jens-maus** [comment] 2020-02-10 15:04
I just checked the relevant code passage/function that your report is referencing:

```js
isDutyCycleOK4DevUpdate = function() {                                         
  var ifaceBidCosRF = "BidCos-RF";          
  var BidCosIFaces = homematic("Interface.listBidcosInterfaces", {"interface": ifaceBidCosRF});
  var dcVal = 0,                                                          
    dcWarningLevel = 80,                                    
    dcOK = true;                                                                          
                                                                          
  jQuery.each(BidCosIFaces, function (index, iFace) {       
    if (iFace.type == "CCU2") {                                                           
      dcVal = (typeof iFace.dutyCycle != "undefined") ? parseInt(iFace.dutyCycle) : 0;
      if (dcVal >= dcWarningLevel) {                        
        dcOK = false;                                                                     
      }                                                                   
      return false; //leave each loop                       
    }                     
  });                                    
  return dcOK;                       
};                                                                               
```
For you it seems to crash in the `jQuery.each()` call. To clarify, can you please tell me if you have any BidCos-RF device and which RF module (RPI-RF-MOD or HM-MOD-RPI-PCB) you are using with RaspberryMatic?!? My guess is that you are not using any RPI-RF-MOD/HM-MOD-RPI-PCB but simply a HmIP-RFUSB which is a HmIP-only RF stick. Is this correct?

**Comment by floriandrott** [comment] 2020-02-11 07:52
Thanks for the quick help. Unfortunately I get an error when I try to update RasperryMatic via the WebUI.
<img width="479" alt="Bildschirmfoto 2020-02-11 um 08 51 22" src="https://user-images.githubusercontent.com/53261305/74218994-c7987f00-4cab-11ea-93a4-8929ea595aa3.png">

You are right. I use the HmIP-RFUSB due to the fact that I have only HmIP-only devices.

**Comment by floriandrott** [comment] 2020-02-11 07:53
I used following zip for my tryout: https://pipelines.actions.githubusercontent.com/O1lNQly8nrBoURpGhPjVJaQleG3Q0Txwsp4Femqdi66t21PN7h/_apis/pipelines/1/runs/106/signedartifactscontent?artifactName=RaspberryMatic-3.51.6.20200210-6474dc6-ova&urlExpires=2020-02-11T07%3A49%3A26.2983669Z&urlSigningMethod=HMACV1&urlSignature=rrjxbsev%2FKJiEg%2Ff4jgYxzUzz%2BFIUcty6fzWQ8blEMk%3D

**Comment by jens-maus** [comment] 2020-02-11 10:12
Then download the latest 3.51.6 nightly snapshot from here, please:
https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

**Comment by floriandrott** [comment] 2020-02-11 11:33
@jens-maus will do. The CI pipeline failed on the OVA build and there is currently no build available.

**Comment by jens-maus** [comment] 2020-02-11 14:22
@floriandrott Then wait for the next nightly build to appear. I just fixed some issues in the CI piplelines and the next build should hopefully finish correctly.

And if you just use a HmIP-RFUSB I think I know where the issues comes from. Will have to develop a fix for it and let you know as soon as you can test it.

**Comment by jens-maus** [comment] 2020-02-11 14:47
As you can see, I just committed a potential fix for your reported issue. So please wait for the next nightly build to appear and retest again if you have a test installation and see if this fixes your WebUI based device update issues.

**Closed** 2020-02-11 14:46 UTC
Labels: :anchor: upstream issue, :bug: bug, :label: WebUI

**Comment by floriandrott** [comment] 2020-02-29 17:48
Thanks @jens-maus - with the new official version it's working!
