### ISSUE TITLE
Fault in "Reboot-waiting-Screen"

### ISSUE THREAD

**Issue by sailor79** [jens-maus/RaspberryMatic#47] opened 2017-01-16 11:49 UTC
<img width="444" alt="bildschirmfoto 2017-01-16 um 12 46 23" src="https://cloud.githubusercontent.com/assets/1407792/21981938/29867a7c-dbea-11e6-9203-c2dfee84abc3.png">

**Comment by jens-maus** [comment] 2017-01-16 12:05
This is a duplicate of #46, which was already fixed BTW.

**Closed by jens-maus** 2017-01-16 12:05 UTC
Labels: bug, duplicate
