### ISSUE TITLE
WebUI: (un)expected behavior of "Systemprotokoll"

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#247] opened 2018-01-20 09:15 UTC
Firmware used: `2.29.23.20171216`

When opening the Systemprotokoll, the entries are listed by **date** ascending (latest entry is the last at the bottom).
But after klicking "Aktualisieren" the list is now sorted by **time**.

And btw: After doing an export, the export file contains more rows than the Systemprotokoll shows in WebUI.

I've created a short [screencast](https://www.dropbox.com/s/3ol2st2k5fuqm5x/HM_Systemprotokoll.mov?dl=0). 
Please take a look.

Thx!
Jérôme

**Comment by jens-maus** [comment] 2018-01-20 18:23
Isn't this a duplicate of #124 ?

**Comment by jp112sdl** [comment] 2018-01-20 18:51
Oh yes, in relation to the sorting issue, it is a duplicate.

But is the behavior of the export function correct? 
I see 11 rows in WebUI and I get 36 line in the exported csv file?
May I open an issue at the OCCU repository?

**Closed** 2020-10-16 15:29 UTC
Labels: :bug: bug-report, :label: WebUI
