### ISSUE TITLE
Provide RaspberryMatic as Docker image

### ISSUE THREAD

**Issue by steff517** [jens-maus/RaspberryMatic#192] opened 2017-11-18 06:21 UTC
I'd be great if RaspberryMatic was available as docker image. Is that possible at all?

**Comment by jens-maus** [comment] 2017-11-18 12:46
Yes, it should be possible but has low priority currently. However, feel free to contribute if you can spare some time and work on docker support.

**Comment by litti** [comment] 2017-11-18 22:16
Here some work regarding docker and rpi can be found: https://github.com/angelnu/docker-ccu2

**Comment by omo2002** [comment] 2018-08-15 08:25
Want to follow up on this. 
I use angelnu's docker solution. But unfortunatelly this does not support homematic IP.

Are there any thoughts to work on a "full" raspberrymatic docker solution ?

**Comment by jens-maus** [comment] 2018-08-15 08:29
As said earlier. I do have plans to work on a docker and also LXC-based RaspberryMatic in future. For docker a basic docker defconfig file for buildroot already exists (see https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/configs). So if you have some time to share, please feel free to contribute.

**Comment by omo2002** [comment] 2018-08-15 18:32
I would love to support, I fear my skills are not sufficient.

**Comment by jens-maus** [comment] 2018-12-14 09:32
Duplicate of #357

**Closed by jens-maus** 2018-12-14 09:32 UTC
Labels: enhancement, hardware support, low priority
