### ISSUE TITLE
Unable to upgrade on a Odroid C4

### ISSUE THREAD

**Issue by Ron-4D** [jens-maus/RaspberryMatic#2572] opened 2023-12-21 17:41 UTC
### Describe the issue you are experiencing

When doing the automatic upgrade from 3.71.12.20231020 to 3.73.9.20231130 the system stops working. Also a fresh install of 3.73.9.20231130 will not boot. Downgrading to 3.71.12.20231020 fix the problem.
I think this is specific to Odroid C4.

### Describe the behavior you expected

A normal boot. The blue leds are not flashing. So I think there is a boot problem.

### Steps to reproduce the issue

1. Just install 3.73.9.20231130
2. Power it up
3. Nothing happens
...

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

odroid-c4 (ODROID C4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Lucky I have a backup ;-)
```

**Comment by jens-maus** [comment] 2023-12-21 19:51
Duplicate of #2546

**Closed** 2023-12-21 19:52 UTC
Labels: :bug: bug-report, :heavy_multiplication_x: duplicate
