### ISSUE TITLE
Firmware update for Blind Actors not working

### ISSUE THREAD

**Issue by martz170** [jens-maus/RaspberryMatic#92] opened 2017-04-14 12:26 UTC
Update termitates when updating FW for  "HM-LC-Bl1PBU-FM" Blind Actors on Raspberry 3 with Version 2.27.8.2017041 and also on Version  2.27.8.20170413. Actors stuck on Boot Loader. When connecting to CCU 2 ( with older Software ) Firware Update starts and ended successfully.

**Comment by jens-maus** [comment] 2017-04-14 17:01
This is a duplicate of #52 - thus closing it.

**Closed by jens-maus** 2017-04-14 17:01 UTC
Labels: bug, duplicate
