### ISSUE TITLE
[Feature request] Automatically identify host device

### ISSUE THREAD

**Issue by jottr** [jens-maus/RaspberryMatic#980] opened 2020-11-03 19:54 UTC
**Is your feature request related to a problem? Please describe.**

There exist a multitude of OS specific releases of RaspberryMatic.
![image](https://user-images.githubusercontent.com/2744198/98033088-45da1a00-1e15-11eb-9670-fed0a6f1af53.png)

It is sometimes difficult to asses the host hardware without physical access.
Users are often unaware that they could check the host device by 
1. Enabling SSH in the frontend
2. Querying `/proc/device-tree/model`

Example for my device:

 ```
# grep Model /proc/device-tree/model
Raspberry Pi 2 Model B Rev 1.1
```

This makes the OS update process unnecessarily difficult and error prone.

**Describe the solution you'd like**

Automatically query `/proc/device-tree/model` for the type of host device RaspberryMatic is running on.
Present the user with the appropriate link to the OS update package for their specific model.

Bonus:

Automate the download and installation of updates.

**Comment by jens-maus** [comment] 2020-11-03 23:29
This refs and is a partly a duplicate of #616

**Closed by jens-maus** 2020-11-03 23:29 UTC

**Comment by jottr** [comment] 2020-11-04 13:21
The related issue #616 has a significantly larger scope than what I am proposing here.
A small script that queries the device-tree and then displays the Model information on the frontend would be a nice first step.
A link to the binary could be a second.
The __Bonus__ (see previous comment) is partially duplicated in #616.

I'd implement this myself, but I can't find any documentation on the architecture of RaspberryMatic.
[This](https://github.com/jens-maus/RaspberryMatic/wiki/Support#mitarbeit--weiterentwicklung) is all that I could find.
 
Am I looking in the wrong places? 
Some pointers would be nice.

**Comment by jens-maus** [comment] 2020-11-04 13:26
@jottr Sorry, but instead of simply adding a link and/or device model info the WebUI, I would like to give #616 more priority as I feel if we touch this area now anyway we should better go for the bigger than and integrate it nicely. Users have lifed with it so long already and given they know the hardware they are using simply displaying a link and/or device tree model info doesn't help a lot. Furthermore, with the upcoming 64bit version of RaspberryMatic RaspberryPi2 users have to switch installation archives and reinstall their SD card anyway. Thus, no easy way to go.

And last not least I have heard that eQ3 is working on such an auto-download mechanism themself. Thus, we should probably better wait what they will come up with in the next upcoming firmware updates.

So sorry, but I still see no benefit in working on this right now.

**Comment by jottr** [comment] 2020-11-04 13:35
Thank you for the insight!
Where can I find further information on the architecture?
It is quite difficult to understand all the moving parts without prior knowledge of the project.

**Comment by jens-maus** [comment] 2020-11-04 13:39
What do you mean exactly about "architecture"? RaspberryMatic is using buildroot/Linux for the OS stuff, and OCCU for the homematic/CCU stuff which is published by eQ3. And sorry, no big time for documentation here (as usual). So feel free to ask specific questions (but probably better in the german speaking HomeMatic Forum, if possible).
