### ISSUE TITLE
Device Firmware Update Problems

### ISSUE THREAD

**Issue by HMside** [jens-maus/RaspberryMatic#52] opened 2017-01-23 17:24 UTC
The following reports points seem to point at some severe problems in trying to update certain device firmwares:

* https://homematic-forum.de/forum/viewtopic.php?f=65&t=36791&p=357995#p357465
* https://homematic-forum.de/forum/viewtopic.php?f=65&t=34497&p=333153#p333153
* https://homematic-forum.de/forum/viewtopic.php?f=65&t=36725
* https://homematic-forum.de/forum/viewtopic.php?f=65&t=36801

According to these reports the following devices seem to be affected:

* HM-LC-Dim1TPBU-FM
* HM-LC-Dimm1T-PL-3
* HM-LC-Bl1PBU-FM

Symptoms always look quite similar:

1. Firmware Update doesn't succeed
2. Actuator stops in boot loader and is afterwards unusable anymore
3. Firmware Update can be continued/finalized using a restored Backup on a real CCU2

**Comment by jens-maus** [comment] 2017-01-29 19:41
As I don't have such a PWM dimmer myself I cannot state if this really is an issue or not.

**Comment by jens-maus** [comment] 2017-02-07 13:40
Have you tried updating that device with a CCU2? As I said, I don't have such a PWM dimmer device at hand and can therefore not help in investigating this issue.

**Comment by hans-peter123** [comment] 2017-02-15 11:31
I had such a problem by myself, my dimmer stuck in the bootloader...
I downgradet my Raspberry to my previous SD image (BUT it was a other Homematic Raspberry System such as LXCCU!) in there the dimmer was recognize and the Update started...
So your dimmer is not broken, its possible to rescue your him!

Maybe i could help you

**Comment by Gerti1972** [comment] 2017-02-25 15:11
I can reproduce same issue with Firmwareupdate of regular Dimmer HM-LC-Dim1TPBU-FM (not PWM) and another user just reports also this issue. It seems that beta4 of Raspberrymatic has general issue in updating devices. It shows error message that device could not be reached and should be taken closer to the CCU. The devices are already in Bootloader mode if the error appers. They can be finally updated by making backup in RaspberryMatic, installing this backup on a CCU and finalize the update with the CCU.

**Comment by jens-maus** [comment] 2017-03-16 12:45
More reports on problems updating dimmer device firmware, see https://homematic-forum.de/forum/viewtopic.php?f=65&t=34497&start=860#p349662

**Comment by jens-maus** [comment] 2017-03-27 08:30
flagging this as a potential upstream issue since we cannot explain it any further.

**Comment by jens-maus** [comment] 2017-04-11 09:43
Now that 2.27.8.20170410 had been released yesterday, can someone please investigate or try to reproduce if the problem still exists?

**Comment by Gerti1972** [comment] 2017-04-11 16:30
There was just a new Firmware for the Blind Actuator released. Same issue here. After starting the Update, Device stucks in Bootloader.

**Comment by jens-maus** [comment] 2017-04-11 17:28
Which device do you mean? Please state the exact name/ID.

**Comment by Gerti1972** [comment] 2017-04-11 17:30
Funk-Rollladenaktor 1-fach für Markenschalter Firmware V2.11.1
Kurz-Bez.: HM-LC-Bl1PBU-FM
Download-Art: Firmware
Artikel-Nr.: 103038

Canhgelog:
Version 2.11.1 - 20161209
--------------------------------------------------------------
** Improvement
	 * Optimization of internal EEPROM handling

http://www.eq-3.de/Downloads/Software/Firmware/HM-LC-Bl1PBU-FM_update_V2_11_1_161212.tgz

**Comment by pedromania** [comment] 2017-04-17 15:41
CCUpi-FW:  2.27.8.20170413

I got stuck with the FW update of the HM-LC-Bl1PBU-FM (103038), too.
I tried to update from 2.8 to v2.11.1.
The LED on the actor is flashing continously in a high frequency.

Need additional info for debugging?

![image](https://cloud.githubusercontent.com/assets/25853558/25093871/ae73b08c-2394-11e7-9448-fe8b7565211a.png)

**Comment by dehell** [comment] 2017-04-20 06:50
I have the same issue with the same configuration as pedromania. The blind actuator is stuck in the bootloader with flashing led. This seems to influence even the radio duty cycle. Since then it's permanently stuck above 90%, limiting the function of the whole system. Any help to get this resolved?
According to some forum entries the update could still be done via a CCU2. Will try this later.

**Comment by marcprenger** [comment] 2017-04-20 12:10
I'm able to confirm this issue. Two of my HM-LC-Bl1PBU-FM blind actuators stuck in bootloade mode after upgrading to 2.11 firmware.

**Comment by edvhoschi** [comment] 2017-04-20 17:10
I had yesterday the same problem with the update of two HM-LC-Bl1PBU-FM. After research at the Homematic forum, there was the problem already with the CCU. Just start again the update and then it goes, if the duty cycle is not too high. I had to turn off an actor yesterday. Today I have then eight more without problems update one after another, duty cycle under control. I have a Raspberry Pi 3 with Funkmodul and 2 more LAN Gateway. Currently, this is the 2.27.8.20170413. So it should not be a basic RaspberryMatic problem, at least not with me.

**Comment by Gerti1972** [comment] 2017-04-20 17:13
Are they routed directly to the Raspberry or are they connected to the LAN-Gateway?

**Comment by dehell** [comment] 2017-04-20 19:51
Very different for me. After the first try the duty cycle didn't go down below 90%, even a day of waiting. The update is now done via my CCU2, 2.25.15. By the way, what's with the duty cycle issue. Is it closed, solved?

**Comment by jens-maus** [comment] 2017-04-20 21:11
See also here for similar reports for plain CCU2 installations: https://homematic-forum.de/forum/viewtopic.php?f=31&t=36761

**Comment by Gerti1972** [comment] 2017-04-21 04:31
The issue on updating devices with Raspberrymatic does not belong to the DutyCycle problem. It also happens with a very low DutyCycle which is far below 100.

**Comment by marcprenger** [comment] 2017-04-21 06:04
DC is not the issue. I restarted my RPI several times in order to reset the DC. 

Here is a log what happening during a failed upgrade:

`Apr 20 13:21:56 homematic user.debug rfd: Event: OEQ00*******:0.UPDATE_PENDING=true
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:56 homematic user.err rfd: Pendingupdate faild!! Firmware update aborted
Apr 20 13:21:56 homematic user.debug rfd: Sysinfo received by NEQ13******* while not in install mode: (unknown type)
Apr 20 13:21:56 homematic user.debug rfd: Sysinfo received by NEQ13******* while not in install mode: (unknown type)
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:56 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:58 homematic user.debug rfd: RX for OEQ0042589: @2333666396 RSSI=-128dB 0x5532F7 -> 0x000000 Generic [NEQ13*******]:   CNT=0,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x10   DATA = 00 4F 45 51 30 30 34 32 35 38 39
Apr 20 13:21:58 homematic user.debug rfd: Event: OEQ0042589:0.UNREACH=false
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:58 homematic user.debug rfd: (NEQ13*******) Response status: OK, Data.
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:58 homematic user.debug rfd: TX:  @2333666399 0x4F6363 -> 0x5532F7 CONFIG_START [NEQ13*******]:   CNT=13,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01   CONFIG_CHANNEL = 1   CONFIG_PEER_ADDRESS = 0x000000   CONFIG_PEER_CHANNEL = 0   CONFI
Apr 20 13:21:58 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Send failed.
Apr 20 13:21:59 homematic user.debug rfd: Event: OEQ0042589:0.UNREACH=true
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: Event: OEQ0042589:0.STICKY_UNREACH=true
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: SendFrame failed 1 times:  @2333666399 0x4F6363 -> 0x5532F7 CONFIG_START [NEQ13*******]:   CNT=13,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01   CONFIG_CHANNEL = 1   CONFIG_PEER_ADDRESS = 0x000000   CONFIG_PE
Apr 20 13:21:59 homematic user.debug rfd: Saving device OEQ0042589
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: RX for OEQ00*******: @2333668050 RSSI=-75dB 0x56020E -> 0x000000 Generic [NEQ13*******]:   CNT=0,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x10   DATA = 00 4F 45 51 30 30 34 30 30 31 37
Apr 20 13:21:59 homematic user.debug rfd: UpdateFile::Read(): Lade Firmwaredatei /etc/config/firmware//106/HM-LC-Bl1PBU-FM_update_V2_3_0002_131204.eq3
Apr 20 13:21:59 homematic user.debug rfd: UpdateFile::Read(): ------- Datei geladen -------
Apr 20 13:21:59 homematic user.debug rfd: TX:  @2333668061 0x4F6363 -> 0x56020E Generic [NEQ13*******]:   CNT=119,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0xCB   DATA = 10 5B 11 F8 15 47 0B 08 1A 1C 19 1D 1B C7 1C 00 1D B2 21 B6 23 EA
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: TX:  @2333668106 0x4F6363 -> 0x56020E Generic [NEQ13*******]:   CNT=120,RPTEN=0,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0xCB   DATA = 10 5B 11 F8 15 47 0B 08 1A 1C 19 1D 1B C7 1C 00 1D B2 21 B6 23 EA
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent, received ACK.
Apr 20 13:21:59 homematic user.debug rfd: Response accepted:  @2333668137 RSSI=-198dB 0x56020E -> 0x4F6363 ACK [NEQ13*******]:   CNT=120,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x02
Apr 20 13:21:59 homematic user.debug rfd: Event: OEQ00*******:0.DEVICE_IN_BOOTLOADER=true
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send 1 events
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: Saving device OEQ00*******
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: HSSXmlRpcEventDispatcher::Handle send completed
Apr 20 13:21:59 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:21:59 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:21:59 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent, received ACK.
Apr 20 13:22:00 homematic user.debug rfd: Response accepted:  @2333668359 RSSI=-128dB 0x56020E -> 0x4F6363 ACK [NEQ13*******]:   CNT=1,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x02
Apr 20 13:22:00 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:22:00 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:22:00 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:22:00 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:22:00 homematic user.debug rfd: Send UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent successfully.
Apr 20 13:22:00 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:00 homematic user.debug rfd: (NEQ13*******) Response status: Telegram sent, received ACK.
Apr 20 13:22:00 homematic user.debug rfd: Response accepted:  @2333668565 RSSI=-128dB 0x56020E -> 0x4F6363 ACK [NEQ13*******]:   CNT=10,RPTEN=0,RPTED=0,BIDI=0,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x02
Apr 20 13:22:00 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:01 homematic user.debug rfd: (NEQ13*******) Response status: Send failed.
Apr 20 13:22:01 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:03 homematic user.debug rfd: (NEQ13*******) Response status: Send failed.
Apr 20 13:22:03 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:04 homematic user.debug rfd: (NEQ13*******) Response status: Send failed.
Apr 20 13:22:04 homematic user.debug rfd: Send Final UpdateTelegram
Apr 20 13:22:06 homematic user.debug rfd: (NEQ13*******) Response status: Send failed.
Apr 20 13:22:06 homematic user.err rfd: Firmwareupdate feur das Ger�t mit der Seriennummer OEQ00******* ist fehlgeschlagen
Apr 20 13:22:06 homematic user.err rfd: Firmware update faild! Firmware update aborted`

I would say that the upgrade was correctly transfered to the acuator - only the last "Final Upgrade Telegram" is not acknowledged.

**Comment by sailor79** [comment] 2017-04-23 05:45
same issue like @pedromania for me

**Comment by FunnyPalatine** [comment] 2017-04-23 19:01
What is the strategy regarding this behavior? Is it recommended to send the devices in bootloader mode to eQ3 in order letting them flash the new firmware or is there a chance that it will be fixed after some time?
Thanks and regards, Michael

**Comment by HMside** [comment] 2017-04-26 17:11
In my update test for HM-LC-Bl1PBU-FM i got an error message (unable to set datarate to 100k) when the device is offline (powered off). Screenshot over here: [https://homematic-forum.de/forum/viewtopic.php?f=65&t=36791&p=358593#p358593](url)

**Comment by awittenburg** [comment] 2017-05-02 06:08
Hi, 

same issue like @pedromania.

I am currently on 2.27.7.20170316 and two roller shutter actors of type HM-LC-Bl1PBU-FM are stuck in boot loader after trying a firmware update 2.8 -> 2.11 .

I will update to newest RasperryMatic firmware on the next weekend. If I can help with any logs etc., please let me know.

**Comment by jens-maus** [comment] 2017-05-02 07:29
@awittenburg An update to the latest version (2.27.8.20170501) won't change anything. The reason for the firmware update problems have already been reported to eQ3 and they are currently working on a rf-module firmware update to solve the issue (it has been identified). Thus, in one of the next official CCU firmware updates this issue should be solved and then a further OCCU update will also solve it for  RaspberryMatic. This is the current state of affairs.

**Comment by awittenburg** [comment] 2017-05-02 08:18
@jens-maus thanks Jens! Is there any known workaround to get the actor working (with old firware) without having an EQ3 CCU2 hardware?

**Comment by HMside** [comment] 2017-05-13 09:04
The device update for HM-LC-Dim1PWM-CV now works with the new dualcopro firmware 2.8.5, tested under 2.27.8.20170413.

Steps to get the new firmware:
`mount -o remount,rw /`
`mv /firmware/HM-MOD-UART/dualcopro_si1002_update_blhm.eq3 dualcopro_si1002_update_blhm.eq3.old`
`wget --no-check-certificate -O /firmware/HM-MOD-UART/dualcopro_si1002_update_blhm.eq3 https://github.com/eq-3/occu/raw/master/firmware/HM-MOD-UART/dualcopro_si1002_update_blhm.eq3`

Also change the version `2.8.4` in /firmware/HM-MOD-UART/fwmap to `2.8.5` and reboot

After perform this update i got a error message all 30 seconds. I dont know if this is related to this update:
`local0.err ReGaHss: Error: CompatibleForCompare of ISEVALUE unknown not supported! [../Platform/DOM/iseValue.cpp (411)]`

**Comment by FunnyPalatine** [comment] 2017-05-19 19:55
I have just successfully upgraded four blind actors that stuck in bootloader mode before. Many thanks!!

**Comment by jens-maus** [comment] 2017-05-22 08:24
With the latest dualcopro firmware the problem seem to be resolved. The next RaspberryMatic version will include this copro firmware. Thus, closing this issue.

**Closed by jens-maus** 2017-05-22 08:24 UTC
Labels: bug, upstream issue

**Comment by awittenburg** [comment] 2017-05-22 19:35
I can confirm that the update worked for stuck HM-LC-Bl1PBU-FM.

Thanks!

**Comment by Holgermatic** [comment] 2017-05-22 21:03
Hi. I had the same problem described in this thread.
But now i have one question. What i have to do for this "Also change the version 2.8.4 in /firmware/HM-MOD-UART/fwmap to 2.8.5 and reboot" ?
The first part was succesfully but im not skilled enough in shell for that.
Sorry for my question.

**Comment by awittenburg** [comment] 2017-05-22 21:16
@Holgermatic You have to edit the file fwmap with an editor during your ssh session. vi is installed so maybe use this one. Basic commands for vi can be found if you google "vi quick reference". But before editing, make a copy of the file using cp command... in case you need to undo changes.

**Comment by Holgermatic** [comment] 2017-05-22 21:34
It works! Thanks alot. 👍

**Comment by renne** [comment] 2017-06-27 11:23
Today I received a replacement HM-LC-Bl1PBU-FM and ran into the same problem again. The RF-firmware version in RaspberryMatic-2.27.8.20170620-rpi0.img seems to be inconsistent:
```
# cat /var/rf_firmware_version
2.8.4
```
```
# cat /firmware/HM-MOD-UART/fwmap
#Type           Filename                Version

#Coprozessor
#CCU2                    coprocessor_update.eq3                          1.4.1          #CoProzessor CCU2  (HM-MOD-UART)

CCU2					dualcopro_si1002_update_blhm.eq3				2.8.5		   #Dual CoProzessor CCU2
```

I changed /var/rf_firmware_version to 2.8.5 with vi. After every reboot it is back to 2.8.4.

**Comment by jens-maus** [comment] 2017-06-27 11:26
@renne Of course, `/var/rf_firmware_version` is just for "reading" the current firmware version not for changing it. Please have a look at the boot up output (ALT+F2) during boot up and what the FirmwareUpdate step says when running the firmware update.

**Comment by renne** [comment] 2017-06-27 12:30
@jens-maus Except an exit status 132 from pdetect the co-processor update is disabled `disabled, OK`. Service messages lists a pending firmware update and the blind actuator being in bootloader mode.

**Comment by jens-maus** [comment] 2017-06-27 12:33
@renne Which version of RaspberryMatic are you using? Which RaspberryPi Hardware are you using? It really is strange that the firmware update replies with a "disabled" message. This usually only happens if the rf-module isn't correct installed on the GPIO.

**Comment by renne** [comment] 2017-06-27 12:56
I checked the rf-module. It's installed correctly. All other sensors/actuators are working fine. The RaspberryMatic version is from the 20.06. on RPi 1B/512.

**Comment by jens-maus** [comment] 2017-06-27 12:59
As said, it shouldn't print "disabled". This is only the case if the file `/etc/config/no-coprocessor-update` exists or if the file `/var/rf_address` is empty or doesn't exist (see https://github.com/jens-maus/RaspberryMatic/blob/2.27.8.20170620/buildroot-external/overlay/base/etc/init.d/S59FirmwareUpdate#L18)

So please check these two files and report back.

**Comment by renne** [comment] 2017-06-27 13:12
After deleting `/etc/config/no-coprocessor-update`:
`Performing coprozessor Update: Ok`
```
# cat /var/rf_firmware_version
2.8.5
```
The firmware update of the blind actuator worked and the actuator itself works too, now. :)

**Comment by jens-maus** [comment] 2017-06-27 13:29
How come that you had this file installed?!?

**Comment by jens-maus** [comment] 2017-06-27 14:02
Yes and there is no other way than manually adding this file. You must have added it manually at some pointY

**Comment by renne** [comment] 2017-06-27 14:07
I did a lot of re-configuring in April when nobody knew why the firmware updates of the HM-LC-Bl1PBU-FM where failing. Maybe I read it in one of the many howtos I tested to get the HM-LC-Bl1PBU-FM up again and it was inherited in the backup.
