### ISSUE TITLE
RPi3b - Performance Issue (Duty Cicle on 99%) since 3.51.6.20200229

### ISSUE THREAD

**Issue by prometheus247** [jens-maus/RaspberryMatic#798] opened 2020-03-04 13:00 UTC
Hi,

**Used Platform:** RaspBerry 3 B+
**Former Patchlevel:** 3.49.17.2019122
Duty Cycle Niveau: ~30%

**Recent Patchlevel:** 3.51.6.20200229
Duty Cycle Niveau: 99%

Once rebooted, within 10 minutes the load goes up to 99%.
I did not change programs or configuration upfront patching.  
What may I provide to identify this furthermore? If you chose to investigate ofc.
I saw this happening here: https://github.com/jens-maus/RaspberryMatic/issues/693

Same HW, same symptomatic, different version.
I am going to downgrade to the former version soon. Whole System is unusable 

PS: Im happy with english or german reply.

**Comment by stimpy23** [comment] 2020-03-30 06:13
Same for me (99% Duty Cycle), but it also started opening and closing our front door several times every morning.
I do have a program for locking it in the evening and unlocking in the morning, but now it repeats this up to 3 times.. (Open/close/open/close...)
The very same installation is running fine since about a year, only change is the last update...

**Comment by jens-maus** [comment] 2020-04-02 13:11
Sorry, but as staed in #693, DutyCycle related issues are in 99% of the cases user related problems caused by RF interferences or similar programming issues. Thus, closing this as a duplicate of #693.

**Closed by jens-maus** 2020-04-02 13:11 UTC
