### ISSUE TITLE
Display Host Name or custom title / caption on homepage

### ISSUE THREAD

**Issue by itchy3344** [jens-maus/RaspberryMatic#802] opened 2020-03-11 09:48 UTC
**Is your feature request related to a problem? Please describe.**
I'm running a quite large RM installation with 3 RM devices on a local network and one attached via VPN to another location. Major issue is that the web frontend on all 4 devices looks the same on the home page, except for the favorites (which is not always shown). 

**Describe the solution you'd like**
It would be perfect if either the host name of the device or a custom caption is displayed in the title area (where the user name is printed) to distinguish the RM installations.

**Describe alternatives you've considered**
Add the host name or caption to the HTML page caption.

**Additional context**
We need multiple RM because we just renovated the house and installed HM devices just everywhere, exceeding 200 devices to be managed. Each RM is managing one floor + one RM for our office in another town.

**Comment by jens-maus** [comment] 2020-04-02 13:14
Duplicate of #548

**Closed by jens-maus** 2020-04-02 13:14 UTC
