### ISSUE TITLE
lighttpd unresponsive for ~30 minutes after reboot, then watchdog starts it

### ISSUE THREAD

**Issue by dominikandreas** [jens-maus/RaspberryMatic#730] opened 2019-10-31 18:43 UTC
**Describe the bug**
Raspberrypi Zero-W doesn't come back online after updating to 3.47.22.20191026 (AP doesn't register client connection)

**To Reproduce**
Update firmware on PiZero-W from ? to RaspberryMatic-3.47.22.20191026-rpi0.zip.
Not sure which firmware I was on previously, last time I updated was ~3-5 months ago.

**Expected behavior**
Device updates, reboots and comes back online.

Not sure if anyone else had this problem, but I just wanted to report this as soon as possible before others "brick" their RaspberryMatics as well.

**Comment by moj02090** [comment] 2019-11-01 10:44
I recocnized a similar (maybe the same) behaivor with my rasberrypi 1 b+.

I updated the device and after reboot I couldnt connect to the webui anymore. I connected my screen which displays "3.47.22.20191026 - http://IP-ADDRESS" but its not possible to open the Webinterface. No Timeout or similar its just loading and loading all the time.

I reinstalled the raspberrymatic with the new version.The webinterface was accessible with default config. Then I changed some settings (IP Address, new User and Firewall) and after reboot the webinterface was not accessible again

**Comment by jens-maus** [comment] 2019-11-03 21:08
Sorry, but this can't be a general problem as this is the first report that there should be problems with the rpi0 version. Can anyone verify these issues?

**Comment by dominikandreas** [comment] 2019-11-04 06:16
I unfortunately haven't had the time to debug further. But this wasn't the first update I did on the pi0 and I had no issues previously. I also don't recall doing any changes to my setup since the last update. There's still the chance of bad luck, like the power supply having a hiccup during the update. There's nothing that would prevent failure in that case, is there?

**Comment by micklafisch** [comment] 2019-11-05 19:55
Same to me today. I upgraded my RPI3 from 3.47.10.20190713 to the actual release 3.47.22.20191026. The webinterface didn't respone anymore but via ssh i can login. One of my script with a telegram message is starting everytime i reboot the raspberrymatic. It seems only the webinterface stopped working.

**Comment by micklafisch** [comment] 2019-11-05 21:17
News from testing: i used etcher to burn the new blank image 3.47.22.20191026 to the sd card. The system was started from scratch and i configured only ssh. After that i uploaded my backup from yesterday and restored it. After a reboot i have the same problem again. SSH is running, the website is all the time "loading" and nothing is displayed.

**Comment by micklafisch** [comment] 2019-11-05 21:39
now i'm confused: i downloaded the original blank image 3.47.10.20190713 and etched it to the sd. After the same procedure (booted blank, activate ssh, restore backup sbk and reboot) i got the same issue. Now i don't can boot my system with a backup file to the website. What did i do wrong? I restore the backup like https://homematic-forum.de/forum/viewtopic.php?t=37728.

**Comment by micklafisch** [comment] 2019-11-06 06:54
after a nap and two fresh coffee i tried the same procedure again: etched the 3.47.10.20190713, activate ssh, copy and restore backup sbk and reboot. Now i have my system back to work and no idea what was different to yesterday. I let the system on the release and don't try the 3.47.22.20191026 again.

**Comment by jens-maus** [comment] 2019-11-06 10:11
@micklafisch Next time you try to update, please connect a monitor to your PiZeroW and press ALT+F2 on a keyboard and then see if there is any sensible output when it tries to setup the WiFi connection, because that's the only reason I can think of that might cause your issues.

**Comment by micklafisch** [comment] 2019-11-06 11:03
@jens-maus Hit me if i'm wrong but there must be another reason for the failure, because i use a RPI3 connected via LAN.

**Comment by jens-maus** [comment] 2019-11-06 11:16
@micklafisch Ah, ok. then I mixed this up with the initiator of the ticket, sorry. However, would be interesting to debug this further. So if possible, please try an update to the latest 3.47.22 version again, connect a monitor+keyboard and then let it boot and press ALT+F2 to see the console output and then post a screenshot here.

**Comment by micklafisch** [comment] 2019-11-07 18:09
@jens-maus i tried the same procedure today. The system was stucked again after reboot. With a display and akeyboard i saw the following screen:
![IMG_0737](https://user-images.githubusercontent.com/44931749/68415143-f88b8400-0191-11ea-8235-06f896135700.jpg)

**Comment by jens-maus** [comment] 2019-11-07 18:53
Strange, the output looks good and there is no signnof anything being stuck?!! Can you ping and/or ssh to 192.168.12.19 after boot?

**Comment by micklafisch** [comment] 2019-11-07 19:17
Yes, ping and ssh is possible - all the time (also yesterday on my first try)

**Comment by jens-maus** [comment] 2019-11-07 19:36
@micklafisch  So what is then not working?  Have you tried another/different browser? Cleared your Browser cache, etc.?

**Comment by micklafisch** [comment] 2019-11-07 19:50
@jens-maus yes i tried also my ipad which never was logged on the raspberrymatic before. Different browsers, operating systems and devices. All of the rpi3 is working except the webinterface.

**Comment by micklafisch** [comment] 2019-11-07 19:57
@jens-maus update from the front line: now i can reach the webinterface. I let the system the last hour in the "stuck mode". Now the webinterface is responding again and i've got an alarm in the WebUI with "Watchdog was triggered - lighttpd restarted". The trigger time of the alarm was the time when the webinterface was back online - maybe it helps you to find out whats wrong at this point. At the sum i have now the newest release and it works. Thanks for helping trouble shooting.

**Comment by micklafisch** [comment] 2019-11-07 20:01
for all others with the problem: try to give the system much, very much time without any manual reboots or other attempts to bring the system back online.

**Comment by jens-maus** [comment] 2019-11-07 20:24
@micklafisch strange that lighttpd seem to be restarted and thus the webinterface being not responsive. So please look into `/var/log/messages` as well as into `/var/log/lighttpd-error.log` for potential reasons for that.

**Comment by micklafisch** [comment] 2019-11-07 20:43
Yes, its me again =(. 
After a system shutdown and new boot on the correct place of the rpi (was temp attached on tv for trouble shooting) the system shows the same behavior. I can ping/ssh to the rpi but the webinterface is all time loading (different devices/cleared cache for sure). It takes around 30 minutes to get back on the webinterface. The watchdog alarm with lighttp restarted is displayed again. I know every boot need its time, but in my opinion this is too long =). I can't interpret the log, i attached the two logs - maybe you can have a look on it (i renamed the messages to messages.log to upload it and i masqueraded some homematic ids in the log with XXX. 

[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3821587/lighttpd-error.log)

[messages.log](https://github.com/jens-maus/RaspberryMatic/files/3821588/messages.log)

**Comment by jens-maus** [comment] 2019-11-07 21:21
Can you please also upload the lighttpd-access.log? thanks.

**Comment by micklafisch** [comment] 2019-11-08 05:53
Yes, i will upload that file at the weekend. For now i have another sd card with the old release and backup running.

**Comment by jens-maus** [comment] 2019-11-08 07:40
Thanks. Would be interessting to debug this further and find out the root cause why the lighttpd web server seem to be started as non-working and than killed somehow (as the lighttpd-error.log suggests) and then it takes ~30 minutes until the monit watchdog automatically restarts it. This would definitlv need more debugging and it would be great if you could do that. For example. after start and having a non-responsive webserver it would be great if you could ssh to your raspberrymatic and see if any "lighttpd" process is running at all and then check all lighttpd log files in /var/log

**Comment by jens-maus** [comment] 2019-11-08 07:55
@micklafisch Please also have a look at #728 which I just closed as a duplicate of this ticket. The logfiles posted there suggest that this user has the same issue like you. So please work together in identifiying similarities which could explain why the lighttpd webserver shows such a strange behaviour in your installations. And if possible please post your `/var/log/lighttpd-access.conf` logfile also.

**Comment by jens-maus** [comment] 2019-11-08 18:26
Can you  guys tell me if you have your RaspberryMatic configured to obtain its IP address via dhcp or do you use a static ip address arrangement? And can you guys please also post your `/etc/config/netconfig` file content here.

**Comment by micklafisch** [comment] 2019-11-08 19:37
hey together. Im booted the 3.47.22.20191026 again and created all the logs for you. Yes, my system is on static ip connected with cable and no dhcp/wireless. I use a RPI3b for the ccu.

The process list is around 1 minute after boot and 4 minutes

 after boot. If im fast after poweron i can see on the webinterface the splash screen that the system is starting and will redirect me automatically. But this never happens and if i refresh manually the site doesn't load anything in the first 30 minutes.

Here the logs:

[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3825979/lighttpd-error.log)
[messages.txt](https://github.com/jens-maus/RaspberryMatic/files/3825980/messages.txt)
[netconfig.txt](https://github.com/jens-maus/RaspberryMatic/files/3825981/netconfig.txt)
[lighttpd-access.log](https://github.com/jens-maus/RaspberryMatic/files/3825982/lighttpd-access.log)

**Comment by micklafisch** [comment] 2019-11-08 19:50
Now the system is online after 30 minutes of waiting. Here are the logs for now:

[process_afterWebinterface_reachable.txt](https://github.com/jens-maus/RaspberryMatic/files/3826016/process_afterWebinterface_reachable.txt)
[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3826018/lighttpd-error.log)
[messages.log](https://github.com/jens-maus/RaspberryMatic/files/3826019/messages.log)
[lighttpd-access.log](https://github.com/jens-maus/RaspberryMatic/files/3826020/lighttpd-access.log)

**Comment by Christoph-sans-e** [comment] 2019-11-08 20:05
Hier meine Logs (wir hatten Kontakt über das Forum vorhin.

[lighttpd-access.log](https://github.com/jens-maus/RaspberryMatic/files/3826070/lighttpd-access.log)
[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3826071/lighttpd-error.log)
[hmserver.log](https://github.com/jens-maus/RaspberryMatic/files/3826072/hmserver.log)

**Comment by jaschkopf** [comment] 2019-11-09 12:28
Hallo. I have the same problem. Here are my logs: 

[hmserver.log](https://github.com/jens-maus/RaspberryMatic/files/3827269/hmserver.log)
[lighttpd-access.log](https://github.com/jens-maus/RaspberryMatic/files/3827270/lighttpd-access.log)
[messages.log](https://github.com/jens-maus/RaspberryMatic/files/3827271/messages.log)
[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3827272/lighttpd-error.log)

**Comment by Christoph-sans-e** [comment] 2019-11-09 18:07
Do you guys use iobroker and the homematic instances? For me this is the reason.
@Jens:
Habe den Auslöser gefunden! Mehrere Testläufe, bin mir zu 99% sicher.
iobroker ist der Grund. Ich habe die Instanzen hm-rega.0, hm-rpc.0 und hm-rps.1 pausiert und schwups...alles gut. Mir ist aufgefallen, dass die CCU3 und der Homematic-Raspi abgwechselnd erst mal gut starteten. Ich habe überlegt, was dann als nächstes kam...klar, dann habe ich die IP in den Instanzen auf dem iobroker angepasst. Danach ein Neustart führt zu den 30 min, in der die Zentrale nicht erreichbar ist oder ewig im Lademodus auf der Startseite.
Ohne die Hintergründe zu kennen mutmaße ich, dass iobroker bzw. die Instanzen versuchen die Zentrale zu erreichen und das dauerhaft...dieses dauerhafte Aufrufen der IP scheint zum Abbruch der WebUI zu führen...vermutlich ähnlich wie eine DDoS-Attacke bei Webseiten?

Jens, kannst Du dazu etwas sagen? Du weißt ja mehr über die Programmierungen...

**Comment by jaschkopf** [comment] 2019-11-09 18:16
Also ich nutze auch den iobroker der mit mehreren Instanzen auf raspberrymatic zugreift. Hatte auch schon so eine Vermutung das es vom iobroker kommt.

**Comment by Christoph-sans-e** [comment] 2019-11-09 18:23
> Also ich nutze auch den iobroker der mit mehreren Instanzen auf raspberrymatic zugreift. Hatte auch schon so eine Vermutung das es vom iobroker kommt.

Pausiere mal die Instanzen und starte die Zentrale neu...kannst Du meine Vermutung bestätigen?

**Comment by jaschkopf** [comment] 2019-11-09 18:25
Kann ich erst morgen testen, aber scheint plausibel zu sein. Habe auch öfter mal Probleme das meine homematic Instanzen einfach gelb werden im iobroker. Vielleicht hängt das zusammen.

**Comment by Christoph-sans-e** [comment] 2019-11-09 18:42
Das habe ich bisher nicht gehabt. Die laufen stabil bei mir, wenn sie laufen... Bin gespannt, was Jens dazu sagen kann.

**Comment by micklafisch** [comment] 2019-11-09 19:22
Hey guys, i can confirm that behavior too. After i paused the rega and all four rpc instances on iobroker the reboot of the ccu only needs about one minute. When the ccu is up, i can start the paused instances and all is running fine.

**Comment by jens-maus** [comment] 2019-11-09 22:06
Danke erst einmal für die vielen Logfiles. Ob das jetzt von ioBroker kommt, kann ich selbst nicht bestätigen, denn ich nutze auch ioBroker, hab aber solche probleme anscheinend nicht.

Was ich aber aus den logfiles recht konsistent sagen kann ist, das in der lighttpd-error.log man sehr gut sehen kann das aus irgendwelchen Gründen ein lighttpd prozess sich "verabschliedet" und dann lighttpd aber nach 30 Minuten von monit dann neugestartet wird. Hier ein Beispiel:

```
2019-11-06 11:45:20: (server.c.1464) server started (lighttpd/1.4.53) 
2019-11-06 11:45:43: (mod_auth.c.517) password doesn't match for / username: iobroker, IP: 192.168.178.67
2019-11-06 11:45:43: (server.c.2059) server stopped by UID = 0 PID = 636 
2019-11-06 12:12:39: (server.c.1464) server started (lighttpd/1.4.53)
```

Wie man daran sehen kann kommt immer eine "password doesn't match" nachricht gefolgt von "server stopped by UID=0". Und dann dauert es ca. 30 minuten bis lighttpd dann neugestartet wird. Es kann also gut sein das diese "password doesn't match" Nachricht ursächlich dafür ist. Da ich selbst solch eine "Password doesn't match" Nachricht nicht habe würde mich interessieren ob jemand der von dem Problem betroffen ist ggf. in der WebUI die Authentifizierung für XMLRPC aktiviert hat (Sicherheit->Authentifizierung) und dann sein Passwort in ioBroker eingetragen hat.

**Comment by Christoph-sans-e** [comment] 2019-11-09 22:19
Ich habe die Authentifizierung aktiv...und auch das Passwort bei ioBroker eingetragen (anders geht die Kommunikation ja nicht...oder?)

**Comment by jens-maus** [comment] 2019-11-09 22:27
Klar, kannst auch auf die Authentifizierung verzichten. Einfach in der WebUI unter "Einstellungen -> Sicherheit" deaktivieren. Würde mich interessieren ob dann das problem sofort weg ist. Wenn ja, dann vermute ich ein Problem im Authentifizierungsdienst der WebUI. Dann würde ich mehr debugging einbauen um dem auf die schliche zu kommen.

**Comment by jaschkopf** [comment] 2019-11-09 23:00
Also ich hab die Authentifizierung auch aktiv. Mein iobroker läuft übrigens auf einem pi 4 falls das irgendwie relevant ist.

**Comment by jens-maus** [comment] 2019-11-10 07:13
Ok, dann die Authentifizierung bitte mal testweise abschalten und berichten. Meine momentane Vermutung ist, das lighttpd aus irgendwelchen Gründen die Authanfrage so früh bekommt, rega aber noch nicht läuft und aus irgendeinem Grund das den lighttpd blockiert bzw zum absturz bringt.

**Comment by micklafisch** [comment] 2019-11-10 08:21
@jens-maus thats it! Without the active authentification the system start takes about 1 minute and everything is up.

**Comment by jens-maus** [comment] 2019-11-10 08:36
Perfect! However, now we need to identify the root cause why lighttpd crashes/stalls if authentification is activated. Do you guys have any special characters in your used auth passwords? Can you please enable auth again but use a simple password (1234) for testing that?!?

**Comment by micklafisch** [comment] 2019-11-10 09:06
I didn't used special characters. For example my Password was „ab1Cde“ (without the quotes =))

Now i tested it with „1234“ and got the same issue with the ccu.

**Comment by 7542** [comment] 2019-11-10 22:34
Ich bin froh diesen Thread gefunden zu haben, da ich mich seit Wochen mit gleichem Verhalten rumschlage.
Zuerst war nach einem Reboot meiner (**damals noch mit ccu3-3.47.18**) CCU3 die WEBUI nicht mehr erreichbar. Auch nach 1 Tag war ein Login nur über SSH möglich. Auch ein Unterbrechen der Spannungsversorgung half nix. Da ich eh schon geplant hatte auf raspberrymatic umzusteigen formatierte ich eine neue SD-Karte mit RaspberryMatic-3.47.22.20191026-rpi3. Nach Backupeinspielen und einigem Nachkonfigurieren klappte alles wieder. Nur tauchte beim Restarten die watchdogmeldung "lighttpd restarted" auf. 
Auch ich habe einen iobroker auf rpi4 mit Zugriff über Authentifizierung auf CCU laufen.

Ich kann´s zeitlich nicht mehr sicher eingrenzen, aber vor ccu3-3.47.18 hat´s noch keine Probleme gegeben. Den iobroker hatte ich schon zuvor!

**Comment by jens-maus** [comment] 2019-11-13 16:55
Gibt es hier niemanden der mehr debug infos zu diesem Problem hier liefern kann? Ist das Problem definitiv weg wenn man die XMLRPC Authentifizierung deaktiviert?

**Comment by 7542** [comment] 2019-11-13 17:01
Habe i.M. die iobroker-adapter gestoppt und kann nun auch wieder ungestört rebooten. Ohne Authentifizierung habe ich noch nicht probiert. Ich denke aber, dass es hier schon eindeutig bestätigt wurde. 
Sag an, welche Szenarien Du durchgespielt haben willst und welche Protokolle Du von wo brauchst, dann könnte ich am Wochenende das durchspielen und „liefern“.

**Comment by 7542** [comment] 2019-11-13 17:04
was meinst Du zu  ccu3-3.47.18

**Comment by jens-maus** [comment] 2019-11-19 18:42
Am allerbesten wäre es wenn ich mich auf solch einem betroffenen System mal selbst aus der ferne via ssh einloggen könnte wenn das problem gerade existent ist. Dann könnte ich das entsprechend debuggen...

**Comment by jaschkopf** [comment] 2019-11-19 18:46
Ich würde mich dazu bereit erklären wenn du mir erklärst was ich dazu machen muss. Ich hätte morgen ab 16uhr Zeit dafür

**Comment by jens-maus** [comment] 2019-11-19 19:52
@jaschkopf Bevor wir solch eine Aktion starten müssten wir erst noch einmal genau folgendes herausfinden:

1. Ist es wirklich zu 100% bei dir reproduzierbar? D.h. du machst einen reboot von RaspberryMatic und in 10 von 10 fällen ist nach dem Start alles über die HDMI Konsole ordentlich hochgefahren (ALT+F2  auf Tastatur gedrückt zum einsehen von etwaigen problemen) aber danach trotzdem die Zentrale über http://X.X.X.X/ eingabe im Webbrowser nicht erreichbar bzw. lediglich die "Bitte warten" Meldung.
2. Ein Login via SSH ist trotzdem möglich und mit Eingabe von `ps aux | grep lighttpd` gibt er genau was aus?
3. Was ist in der `/var/log/lighttpd-error.log` Datei zu finden?
4. Was gibt während die WebUI nicht erreichbar ist der Befehl `monit status lighttpd` aus?
2. Es dauert dann ca. 30 Minuten bis eine Stunde bis die WebUI final wieder erreichbar ist und es taucht dann eine WatchDog Alarmmeldung danach auf das lighttpd neugestartet wurde?

**Closed** 2019-11-19 23:01 UTC
Labels: :bug: bug, :thumbsup: important

**Comment by jens-maus** [comment] 2019-11-19 23:06
Inzwischen konnte ich erfolgreich das Problem hier selbst in meiner Testinstallation reproduzieren und entsprechend im `mod_authn_rega` lighttpd auth modul reparieren. Das Problem war hierbei, das wenn `ReGaHss` selbst beim Hochfahren der Zentrale noch nicht läuft  aber bereits XMLRPC Authentifizierungsanfragen über den Webserver verarbeitet werden sollen es dazu kam das der Webserver (`lighttpd`) endlos auf eine Antwort von ReGaHss gewartet hat. Dies erklärt auch die nicht erreichbarkeit der WebUI nach dem Hochfahren und das wiederherstellen der Funktionalität durch das manuelle Neustarten des Webservers. Mit dem nun integrierten Fix im auth modul sollte das Problem nun hoffentlich für zukünftige Versionen repariert sein.

**Comment by psytester** [comment] 2019-11-19 23:08
Here are the steps to reproduce the crash at any time.
To simulate a CCU restart we simple restart the ReGaHss to have same condition

Use a remote Linux to start the python script below
Then SSH login on CCU and
stop the ReGaHss process (like in reboot condition)
```/etc/init.d/S70ReGaHss stop```
---> lighttpd stops to process

restart the lighttpd, because its not longer responding
```/etc/init.d/S50lighttpd restart```
---> lighttpd-error.log will contain:
```(mod_auth.c.517) password doesn't match for / username: Admin, IP: 192.168.4.100```
```(server.c.2059) server stopped by UID = 0 PID = 4561```

~~~python
#! /usr/bin/python3

# Title: Let's crash the lighttpd while the Homematic CCU ReGaHss process is not running
# Date: 19.11.2019
# Update: --
# Author: psytester

# Description:
# 1. Start this script from remote system
# 2. On CCU call /etc/init.d/S70ReGaHss stop
#     lighttpd stops to process
# 3. On CCU call /etc/init.d/S50lighttpd restart
#	lighttpd-error.log will contain:
#		(mod_auth.c.517) password doesn't match for / username: Admin, IP: 192.168.4.100
#		(server.c.2059) server stopped by UID = 0 PID = 4561

import http.client
import socket
import time
import os
import datetime

host = '192.168.4.132'
port1 = 80
port2 = 2010

# change the login data (here base64 'Admin:admin') to your settings !!!!
loginData = 'QWRtaW46YWRtaW4='

# Only the POST request will crash the lighttpd
useGET = False
usePOST = True
while True:
	if (useGET == True):
		connection = http.client.HTTPConnection(host, port1, timeout=1)
		connection.request('GET', "/ise/checkrega.cgi")
		try:
			response = connection.getresponse()
			print('{} GET request ok'.format(datetime.datetime.now()))
		except:
			pass
			print('{} GET request FAILED'.format(datetime.datetime.now()))

	if (usePOST == True):
		connection2 = http.client.HTTPConnection(host, port2, timeout=1)
		connection2.request('POST', "/", headers={'Authorization': 'Basic '+loginData})
		try:
			response = connection2.getresponse()
			print('{} POST request ok'.format(datetime.datetime.now()))
		except:
			pass
			print('{} POST request FAILED'.format(datetime.datetime.now()))

print('Finished never reached ;-)')
~~~

**Comment by psytester** [comment] 2019-11-19 23:09
upps, to late....
