### ISSUE TITLE
Enable Diagram when you boot from SSD

### ISSUE THREAD

**Issue by lobocobra** [jens-maus/RaspberryMatic#731] opened 2019-11-02 02:20 UTC
**Is your feature request related to a problem? Please describe.**
I understood well from #421 that if you have no USB stick you can not show diagram.
But I boot directly from a SSD and nod a SD-card, how can I activate diagram?

**Describe the solution you'd like**
I want to have diagram when I boot from SSD

**Describe alternatives you've considered**
Or I would agree to use some space on the NAS

**Additional context**
Can you please tell me how I can activate diagram without adding an USB stick?

**Comment by jens-maus** [comment] 2019-11-03 21:10
Duplicate of #416

**Closed by jens-maus** 2019-11-03 21:10 UTC
Labels: :bug: bug, :heavy_multiplication_x: duplicate
