### ISSUE TITLE
System variable "Anwesenheit"

### ISSUE THREAD

**Issue by PaulMerk** [jens-maus/RaspberryMatic#263] opened 2018-02-15 18:23 UTC
System variable "Anwesenheit" is TRUE after each system start. This is a trap for unexperienced users who expect, that the last state is remaining after system restart, as all other system variables. 
They will be surprised when after power interruption during their holidays the system is working as if they were at home.

This was previously reported in issue #250 and marked as duplicate of issue #223 by Jens. 
However #223 deals with programs after start and not the behaviour of System variable "Anwesenheit" after start .

**Comment by libertyx82** [comment] 2018-02-22 17:09
This is not an Issue of RaspberryMatic.
The official Release for the CCU2 from eq-3 has the same behavior.

**Comment by jens-maus** [comment] 2018-02-26 10:33
This is a duplicate of #250. If you are not happy that your ticket was closed and you need more discussion on it, reopen ticket #250 and continue there.

**Closed by jens-maus** 2018-02-26 10:33 UTC
Labels: duplicate, enhancement
